
import { MORALE_DC } from '../../engine/rulesEngine';
import { SYSTEM_LINES } from '../../services/i18n/systemLines';

/**
 * Les textes (fr / en) des ecrans de ce dossier, une table par composant.
 *
 * Rassembles ici le 2026-08-25 (R8 du rangement) : chaque table vivait en
 * tete de son composant sous le nom TRANS ; le composant l'importe
 * desormais sous ce meme alias, ses usages n'ont pas change. Contenu
 * inchange.
 */

// ── ActionPips ──
export const ACTION_PIPS_TEXTS = {
    en: {
        action: 'Action',
        actions: 'Actions',
        bonus: 'Bonus',
        endTurn: 'End the turn ▸',
    },
    fr: {
        action: 'Action',
        actions: 'Actions',
        bonus: 'Bonus',
        endTurn: 'Terminer le tour ▸',
    },
} as const;

// ── ActionPrompt ──
export const ACTION_PROMPT_TEXTS = {
    en: {
        damageRoll: 'DAMAGE ROLL',
        savingThrow: 'SAVING THROW',
        attackRoll: 'ATTACK ROLL',
        skillCheck: 'SKILL CHECK',
        advantageBadge: 'ADVANTAGE - Roll 2d20, keep highest',
        disadvantageBadge: 'DISADVANTAGE - Roll 2d20, keep lowest',
        inclDmBonus: (b: number) => `(incl. DM bonus ${b >= 0 ? '+' : ''}${b})`,
        rulesContext: 'Rules context',
        rollAdvantage: 'ROLL WITH ADVANTAGE!',
        rollDisadvantage: 'ROLL WITH DISADVANTAGE',
        clickToRoll: 'CLICK TO ROLL',
        cancel: 'Cancel',
    },
    fr: {
        damageRoll: 'JET DE DÉGÂTS',
        savingThrow: 'JET DE SAUVEGARDE',
        attackRoll: "JET D'ATTAQUE",
        skillCheck: 'TEST DE COMPÉTENCE',
        advantageBadge: 'AVANTAGE - Lancez 2d20, gardez le plus haut',
        disadvantageBadge: 'DÉSAVANTAGE - Lancez 2d20, gardez le plus bas',
        inclDmBonus: (b: number) => `(incl. bonus MJ ${b >= 0 ? '+' : ''}${b})`,
        rulesContext: 'Contexte des règles',
        rollAdvantage: 'LANCER AVEC AVANTAGE !',
        rollDisadvantage: 'LANCER AVEC DÉSAVANTAGE',
        clickToRoll: 'CLIQUEZ POUR LANCER',
        cancel: 'Annuler',
    },
} as const;

// ── AuditConsole ──
export const AUDIT_CONSOLE_TEXTS = {
  en: {
    title: '🔍 AUDIT CONSOLE',
    filterPlaceholder: 'filter text…',
    resume: '▶ resume',
    pause: '⏸ pause',
    clear: 'clear',
    exportLog: '💾 export',
    exportTitle: 'Save the displayed entries to a .txt file (respects the filters).',
    devMode: '🛠 Dev Mode',
    on: 'ON',
    off: 'OFF',
    noEntries: 'No entries. Play, talk to the DM, trigger an image/sound… everything shows up here live.',
    copy: 'copy',
    selectEntry: 'Select an entry to see the full detail (prompt, args, response…).',
    noDetail: '(no detail)',
    popupBlocked: "The audit window was blocked by the browser. Allow pop-ups for this site, then try again.",
    windowTitle: "DungeonAI — Audit Console",
  },
  fr: {
    title: '🔍 CONSOLE D\'AUDIT',
    filterPlaceholder: 'filtrer le texte…',
    resume: '▶ reprendre',
    pause: '⏸ pause',
    clear: 'vider',
    exportLog: '💾 exporter',
    exportTitle: 'Enregistre les entrées affichées dans un fichier .txt (filtres pris en compte).',
    devMode: '🛠 Mode Dév',
    on: 'ON',
    off: 'OFF',
    noEntries: 'Aucune entrée. Joue, parle au MJ, déclenche une image/son… tout apparaît ici en direct.',
    copy: 'copier',
    selectEntry: 'Sélectionne une entrée pour voir le détail complet (prompt, args, réponse…).',
    noDetail: '(pas de détail)',
    popupBlocked: "La fenêtre d'audit a été bloquée par le navigateur. Autorise les pop-ups pour ce site, puis réessaie.",
    windowTitle: "DungeonAI — Console d'audit",
  },
} as const;

// ── DeathScreen ──
export const DEATH_SCREEN_TEXTS = {
    en: {
        fallen: 'YOU HAVE FALLEN',
        line: (name: string) => `${name} has succumbed to their wounds. Three death saves failed — the darkness closes in.`,
        resurrect: 'A miracle... at a price',
        resurrectDesc: (gold: number) => `Fate is not done with you. You come back to life with 1 HP — but half your gold (${gold} gp) is claimed by the debt, and you carry a Scar of Destiny forever.`,
        resurrectBtn: 'Accept the pact (revive at 1 HP)',
        end: 'Let the story end',
        endDesc: 'Accept death. Leave this campaign — your saga ends here.',
        endBtn: 'Accept death (back to menu)',
    },
    fr: {
        fallen: 'TU ES TOMBÉ',
        line: (name: string) => `${name} a succombé à ses blessures. Trois jets de mort ratés — les ténèbres se referment.`,
        resurrect: 'Un miracle… à un prix',
        resurrectDesc: (gold: number) => `Le destin n'en a pas fini avec toi. Tu reviens à la vie avec 1 PV — mais la moitié de ton or (${gold} po) est réclamée par la dette, et tu porteras à jamais une Cicatrice du destin.`,
        resurrectBtn: 'Accepter le pacte (revenir à 1 PV)',
        end: "Laisser l'histoire se terminer",
        endDesc: 'Accepter la mort. Quitter cette campagne — ta saga se termine ici.',
        endBtn: 'Accepter la mort (retour au menu)',
    },
} as const;

// ── DiceTray ──
export const DICE_TRAY_TEXTS = {
    en: {
        success: '✓ Success',
        failure: '✗ Failure',
        combatTitle: 'Combat rolls',
        skillTitle: 'Skill rolls',
        combatEmpty: 'Attacks, damage and saving throws will appear here.',
        skillEmpty: 'Skill checks will appear here.',
        rollsTitle: 'Rolls',
        tabAll: 'All',
        tabCombat: 'Combat',
        tabSkill: 'Skills',
        allEmpty: 'Every roll (attacks, damage, saves, checks) will appear here.',
    },
    fr: {
        success: '✓ Réussite',
        failure: '✗ Échec',
        combatTitle: 'Jets de combat',
        skillTitle: 'Jets de compétence',
        combatEmpty: "Attaques, dégâts et sauvegardes s'afficheront ici.",
        skillEmpty: "Les jets de compétence s'afficheront ici.",
        rollsTitle: 'Jets',
        tabAll: 'Tous',
        tabCombat: 'Combat',
        tabSkill: 'Compétences',
        allEmpty: "Tous les jets (attaques, dégâts, sauvegardes, tests) s'afficheront ici.",
    },
} as const;

// ── IntroCinematic ──
export const INTRO_CINEMATIC_TEXTS = {
  en: {
    hero: 'Hero',
    adventureBegins: 'Adventure Begins',
    firstSceneWaits: 'The first scene waits in the dark.',
    openingVeil: 'Opening Veil',
    playIntro: 'Play Intro',
    narration: 'Narration',
    beginScene: 'Begin Scene',
    veilGathers: 'The veil gathers',
  },
  fr: {
    hero: 'Héros',
    adventureBegins: "L'aventure commence",
    firstSceneWaits: 'La première scène attend dans le noir.',
    openingVeil: 'Lever du voile',
    playIntro: "Lancer l'intro",
    narration: 'Narration',
    beginScene: 'Commencer la scène',
    veilGathers: 'Le voile se rassemble',
  },
} as const;

// ── ProposedActionPrompt ──
export const PROPOSED_ACTION_PROMPT_TEXTS = {
    en: {
        actionPrincipale: 'Main action',
        actionBonus: 'Bonus action',
        gratuit: 'Free',
        reaction: 'Reaction',
        improvisedAction: 'Improvised action',
        resolving: 'Resolving…',
        confirm: 'Confirm',
        cancel: 'Cancel',
        advantage: 'advantage',
        disadvantage: 'disadvantage',
        attackRoll: 'Attack roll',
        save: 'Save',
        ifFail: 'if failed',
        check: 'Check',
        autoSuccess: 'Automatic success',
        effect: 'Effect',
        effectApplied: 'Effect applied',
        attackScope: 'attack',
    },
    fr: {
        actionPrincipale: 'Action principale',
        actionBonus: 'Action bonus',
        gratuit: 'Gratuit',
        reaction: 'Réaction',
        improvisedAction: 'Action improvisée',
        resolving: 'Résolution…',
        confirm: 'Confirmer',
        cancel: 'Annuler',
        advantage: 'avantage',
        disadvantage: 'désavantage',
        attackRoll: "Jet d'attaque",
        save: 'Sauvegarde',
        ifFail: 'si échec',
        check: 'Test',
        autoSuccess: 'Succès automatique',
        effect: 'Effet',
        effectApplied: 'Effet appliqué',
        attackScope: 'attaque',
    },
} as const;

// ── ReactionPrompt ──
export const REACTION_PROMPT_TEXTS = {
    en: { reaction: 'REACTION', accept: 'Cast Shield (+5 AC)', decline: 'Take the hit' },
    fr: { reaction: 'RÉACTION', accept: 'Lancer Bouclier (+5 CA)', decline: 'Encaisser le coup' },
} as const;

// ── RollingDice ──
export const ROLLING_DICE_TEXTS = {
    en: {
        defaultReason: 'Check',
        rolling: 'Rolling...',
        dmRolled: 'DM Rolled',
        youRolled: 'You Rolled',
        success: '✓ SUCCESS',
        failure: '✗ FAILURE',
        dismiss: 'Click anywhere to dismiss',
    },
    fr: {
        defaultReason: 'Test',
        rolling: 'Lancer...',
        dmRolled: 'Le MJ a lancé',
        youRolled: 'Vous avez lancé',
        success: '✓ RÉUSSITE',
        failure: '✗ ÉCHEC',
        dismiss: 'Cliquez n\'importe où pour fermer',
    },
} as const;

// ── SettingsPanel ──
export const SETTINGS_PANEL_TEXTS = {
    en: {
        title: 'Settings',
        subtitle: 'Audio, dice, DM voice and local media',
        audio: 'Audio',
        musicVolume: 'Music volume',
        menuMusic: 'Theme on the menu screens',
        menuMusicHint: 'The looping track on login, mode selection, campaign choice and character creation. In-session music is governed separately, below.',
        sfxVolume: 'Sound effects volume',
        dice: 'Dice',
        diceSpeed: 'Dice animation speed',
        speedNormal: 'Normal (3s)',
        speedFast: 'Fast (1.5s)',
        speedInstant: 'Instant',
        diceHint: 'A click on the dice always skips the animation.',
        voice: 'DM voice',
        voiceHint: 'Applied at the next connection (leave and re-enter the session, or wait for a reconnect).',
        media: 'Local media (GPU)',
        localImages: 'Scene images (FLUX)',
        localSfx: 'Sound effects',
        localMusic: 'Music',
        portraits: 'Generated portraits (hero & NPCs)',
        mediaHint: 'Turn these off on a machine without a GPU — the game runs fine without them.',
        imageQuality: 'Scene image quality',
        qualityFast: 'Fast — FLUX.2 klein 4B',
        qualityHigh: 'Quality — FLUX.2 klein 9B',
        imageQualityHint: 'Quality follows the prompt more closely and renders finer detail, for a slightly longer wait. Applies from the next scene onward.',
        gameplay: 'Story mode',
        storyMode: 'Maximized healing (potions & spells)',
        storyModeHint: 'Story-mode comfort: every potion and healing spell restores its maximum. Attacks and saves stay unchanged.',
        reset: 'Reset to defaults',
    },
    fr: {
        title: 'Réglages',
        subtitle: 'Audio, dés, voix du MJ et médias locaux',
        audio: 'Audio',
        musicVolume: 'Volume de la musique',
        menuMusic: 'Thème des écrans de menu',
        menuMusicHint: "La piste en boucle sur la connexion, le choix du mode, la sélection de campagne et la création. La musique en partie se règle séparément, plus bas.",
        sfxVolume: 'Volume des effets sonores',
        dice: 'Dés',
        diceSpeed: 'Vitesse des animations de dés',
        speedNormal: 'Normale (3 s)',
        speedFast: 'Rapide (1,5 s)',
        speedInstant: 'Instantanée',
        diceHint: "Un clic sur le dé saute toujours l'animation.",
        voice: 'Voix du MJ',
        voiceHint: "Appliquée à la prochaine connexion (quitte et reviens en session, ou attends une reconnexion).",
        media: 'Médias locaux (GPU)',
        localImages: 'Images de scène (FLUX)',
        localSfx: 'Effets sonores',
        localMusic: 'Musique',
        portraits: 'Portraits générés (héros & PNJ)',
        mediaHint: "À désactiver sur une machine sans GPU — le jeu fonctionne très bien sans.",
        imageQuality: 'Qualité des images de scène',
        qualityFast: 'Rapide — FLUX.2 klein 4B',
        qualityHigh: 'Qualité — FLUX.2 klein 9B',
        imageQualityHint: "Le mode Qualité suit mieux le prompt et rend plus de détail, pour une attente un peu plus longue. Prend effet dès la scène suivante.",
        gameplay: 'Mode histoire',
        storyMode: 'Soins maximisés (potions & sorts)',
        storyModeHint: 'Confort du mode histoire : chaque potion et sort de soin rend son maximum. Attaques et sauvegardes inchangées.',
        reset: 'Réinitialiser',
    },
} as const;

// ── StatusBar ──
export const STATUS_BAR_TEXTS = {
    en: {
        halfCover: 'Half cover',
        threeQuarterCover: '3/4 cover',
        coverTooltipSuffix: 'AC against ranged attacks',
        turnsShort: 'turn(s)',
        turnAbbrev: 't',
        noActiveEffect: 'No active effect',
    },
    fr: {
        halfCover: 'Demi-couvert',
        threeQuarterCover: '3/4 couvert',
        coverTooltipSuffix: 'CA contre les attaques à distance',
        turnsShort: 'tour(s)',
        turnAbbrev: 't',
        noActiveEffect: 'Aucun effet actif',
    },
} as const;

// ── GameSession ──
export const GAME_SESSION_TEXTS = {
  en: {
    ...SYSTEM_LINES.en,
    railHandle: 'Chronicle width — drag, arrow keys, or double-click to reset',
    devModeOn: '🛠️ *[DEVELOPER MODE ON — the DM now obeys your direct orders. Type IDDAD again to disable.]*',
    devModeOff: '🛠️ *[Developer mode disabled — the DM resumes its normal arbitration.]*',
    connectionRestored: '🔗 Connection restored. You may continue.',
    connectionLostRetry: '⚠️ Connection lost. Reconnecting…',
    connectionLostNotSent: '⚠️ Connection lost. Message not sent. Reconnecting…',
    sendError: '❌ Send error. Please try again.',
    nothingToSave: 'Nothing to save!',
    gameSaved: '💾 Game saved!',
    saveErrorConcurrency: 'Save error (concurrency or empty data).',
    saveError: 'Save error!',
    sagaBegins: 'The saga begins…',
    hero: 'Hero',
    dm: 'DM',
    talkToDM: 'Talk to the DM…',
    reconnecting: 'Reconnecting…',
    send: 'Send',
    micActive: 'Mic active',
    enableMic: 'Enable mic',
    pendingReconnect: 'message(s) awaiting reconnection',
    reconnectTitle: 'Connection lost',
    reconnectReassure: 'The Dungeon Master is coming back. Nothing is lost — your game is saved and your last words are queued.',
    reconnectIn: 'Back in',
    reconnectSeconds: 's',
    reconnectLastTry: 'Last attempt in progress…',
    reconnectAttemptOf: 'Attempt {n} of 3',
    generatingScene: 'Generating the scene…',
    npcTurnInProgress: '🎲 NPC turn in progress…',
    campaign: 'Campaign',
    codex: 'Codex',
    spellbook: 'Spellbook',
    connectionLostSimple: 'Unable to reconnect to the server.',
    reference: 'Reference',
    connected: 'Connected',
    disconnected: 'Disconnected',
    waiting: 'waiting',
    saving: 'Saving…',
    save: 'Save',
    saveFailed: '☁️ Not synced',
    saveFailedTooltip: 'Cloud save is failing — recent progress may not be persisted. Check your connection, then click Save.',
    music: 'Music',
    shortRest: 'Short rest',
    longRest: 'Long rest',
    devBanner: '🛠️ Developer mode — the DM obeys',
    auditTitle: "Audit console (separate window) — system prompts, Gemini, image, SFX, music, combat",
    audit: '🔍 Audit',
    devTooltip: 'Developer mode (the DM obeys your direct orders). Same as typing IDDAD in the chat.',
    dev: '🛠 Dev',
    on: 'ON',
    off: 'OFF',
    loadingCodex: 'Loading the Codex…',
    hp: 'HP',
    levelWord: 'Level',
    combatEndedManually: '⚔️ Combat ended manually.',
    appliedToAttack: 'applied to your attack',
    damage: 'Damage',
    hit: 'HIT!',
    miss: 'MISS',
    critHit: 'CRITICAL HIT',
    touched: 'hit',
    missed: 'missed',
    attackLabel: 'Attack',
    attackN: (n: number, max: number) => max > 1 ? `Attack ${n}/${max}` : 'Attack',
    frenzy: 'Frenzy',
    warPriest: 'War Priest',
    offhandAttack: 'Off-hand attack',
    shieldBash: 'Shield bash',
    vs: 'vs',
    dodgeDesc: 'Active defense. Attacks against you have disadvantage.',
    test: 'check',
    saveWord: 'save',
    saveSuccess: 'succeeded',
    saveFail: 'failed',
    checkSuccess: 'success',
    checkFail: 'failure',
    target: 'target',
    takes: 'takes',
    enemyTargets: (npc: string, t: string) => `🎯 ${npc} targets ${t} (DM's choice)`,
    ac: 'AC',
    potion: 'Potion',
    healing: 'healing',
    abilitySecondWindLabel: 'Second Wind',
    abilityLayOnHandsLabel: 'Lay on Hands',
    abilityBardicLabel: 'Bardic Inspiration',
    abilityFlurryLabel: 'Flurry of Blows',
    abilityPatientLabel: 'Patient Defense',
    abilitySmiteLabel: 'Divine Smite',
    abilityRecklessLabel: 'Reckless Attack',
    abilityStunningLabel: 'Stunning Strike',
    abilityStepWindLabel: 'Step of the Wind',
    abilityTurnUndeadLabel: 'Turn Undead',
    abilityPactFocusLabel: 'Pact Focus',
    abilityNaturalRecoveryLabel: 'Natural Recovery',
    slotsRecovered: (n: number) => `${n} spell slot(s) recovered`,
    martialArts: 'Martial Arts',
    abilityDivineSenseLabel: 'Divine Sense',
    abilitySacredWeaponLabel: 'Sacred Weapon',
    abilityVowLabel: 'Vow of Enmity',
    abilityWrathLabel: "Nature's Wrath",
    abilityChallengeLabel: 'Cavalier Challenge',
    abilityInterventionLabel: 'Divine Intervention',
    abilityPrimevalLabel: 'Primeval Awareness',
    // ── Lignes SYSTEME des capacites de classe (2026-08-27) ──────────────
    // Seul le NOM de la capacite etait traduit : la phrase autour restait en
    // francais dur dans une session anglaise (« +2 degats, resistance… »).
    abRage: '🔥 RAGE — +2 damage, resistance to physical damage (10 rounds)',
    abActionSurge: (n: number) => `⚡ Action Surge — +${n} attack(s) this turn`,
    abBardic: (die: string, bonus: number) => `(${die}) — +${bonus} on an upcoming roll`,
    abPatient: 'Dodge until your next turn',
    abFamiliar: (name: string, kind: string) => `🦉 ${name} (${kind}) harries the enemy — advantage on your next attack`,
    abLucky: (left: number) => `🍀 Lucky — advantage on your next roll (${left} left)`,
    abCunningHide: '🫥 Cunning Action — hidden: advantage on your next attack',
    abCunningDash: '🏃 Cunning Action — Disengage/Dash: you reposition without provoking attacks',
    abGuidedStrike: '⚡ Guided Strike — +10 on your next attack roll',
    abFontOfMagic: '✨ Font of Magic — one level-1 slot created (2 sorcery points)',
    abManeuver: (die: string) => `🎲 Maneuver — +${die} damage on your weapon attacks this round`,
    abWildShape: (hp: number) => `🐻 Wild Shape — ${hp} temporary HP (10 rounds)`,
    abSmiteBurn: (lvl: number, dice: number) => `slot lvl.${lvl} burned: +${dice}d8 radiant on your next hit`,
    abReckless: 'advantage on your attacks this turn, but you leave yourself open',
    abStunning: (dc: number) => `next hit: CON save DC ${dc} or stunned`,
    abStepWind: 'Dash + Disengage',
    abPactFocus: 'advantage on your next spell attack',
    abDivineSense: 'celestials, fiends and undead within 60 ft revealed',
    abSacredWeapon: (bonus: number) => `+${bonus} to attack rolls (10 rounds)`,
    abVow: (foe: string) => `against ${foe} — advantage on your attacks (10 rounds)`,
    abWrathFree: (foe: string) => `${foe} breaks free of the vines`,
    abWrathHeld: (foe: string) => `${foe} is RESTRAINED by the spectral vines`,
    abChallenge: (foe: string) => `${foe} sees no one but you`,
    abInterventionYes: '🌟 DIVINE INTERVENTION — your deity ANSWERS!',
    abInterventionNo: (roll: number, lvl: number) => `the heavens stay silent (${roll} > ${lvl})`,
    abPrimeval: 'the presence of supernatural creatures within 1 mile revealed',
    abQuickened: 'your next spell costs a bonus action',
    abHeightened: 'the next enemy save is made with DISADVANTAGE',
    dcLabel: 'DC',
    abTurnDestroyed: (names: string) => `${names} DESTROYED`,
    abTurnFled: (names: string) => `${names} flee`,
    abTurnNone: 'no undead turned',
    abTurnNoUndead: 'no undead present',
    npcAllyTurn: (name: string) => `Allied ${name}'s turn — the DM directs them`,
    npcPartyDown: 'Defeat — the whole party is down.',
    npcCloseDistance: (name: string, from: string, to: string) => `${name} closes in (${from} → ${to}).`,
    bandFar: 'far', bandNear: 'at range', bandMelee: 'in contact',
    npcMissileCaught: ' — missile CAUGHT!',
    npcHeals: (caster: string, spell: string, target: string, hp: number) => `${caster} casts ${spell} on ${target} — +${hp} HP`,
    gsTurnAdvanced: (who: string) => `Turn advanced to ${who}`,
    gsVictory: (xp: number) => `Victory! +${xp} XP`,
    gsEffectsExpired: (names: string) => `Effect(s) faded: ${names}`,
    gsEffectsExpiredTime: (names: string) => `Effect(s) faded with time: ${names}`,
    gsCombatResumed: 'Combat resumed — it is your move.',
    gsConcentrationHeld: 'Concentration maintained',
    gsPotionDrunk: (name: string, healing: number) => `${name} drunk — +${healing} HP`,
    gsItemUsed: (name: string) => `${name} used`,
    gsStoryModeOn: 'Story mode ON — potions and healing spells restore their maximum',
    gsStoryModeOff: 'Story mode OFF — healing rolls dice again',
    gsRerollLabelIndomitable: 'Indomitable',
    gsRerollLabelInspiration: 'Inspiration burned',
    gsReroll: (label: string, total: number, dc: number, ok: boolean) =>
        `🎲 ${label} — reroll: ${total} vs DC ${dc} (${ok ? 'success' : 'failure'})`,
    aoeDamageRoll: 'area damage',
    hazardDamage: (hazard: string, amount: number, type: string) => `${hazard} — ${amount} ${type} damage`,
    paNoAttackLeft: 'No attack left this turn — end your turn or use a bonus action.',
    paAdvance: (who: string, target: string, from: string, to: string, melee: boolean) =>
        `${who} closes in on ${target} (${from} → ${to})${melee ? ' — in contact, a strike is possible' : ''}.`,
    paDarkBlessing: (hp: number) => `🔥 Dark One's Blessing — ${hp} temporary HP`,
    paBonusUsed: 'Bonus action already used this turn.',
    paMainFirst: 'Attack with your main weapon first — the bonus attack comes AFTER the Attack action.',
    paPotionBuff: (name: string, label: string) => `${name} — ${label} for 1 h`,
    paMainUsedFor: (label: string) => `Main action already used this turn — "${label}" is not possible.`,
    paBonusUsedFor: (label: string) => `Bonus action already used this turn — "${label}" is not possible.`,
    paReactionUsedFor: (label: string) => `Reaction already used this turn — "${label}" is not possible.`,
    abilityQuickenedLabel: 'Quickened Spell',
    abilityHeightenedLabel: 'Heightened Spell',
    abilityWholenessLabel: 'Wholeness of Body',
    rerollIndomitable: 'Reroll with Indomitable',
    reactionUncanny: 'Uncanny Dodge — damage halved',
    reactionDeflect: (n: number) => `Deflect Missiles — ${n} damage deflected`,
    relentlessLine: 'RELENTLESS RAGE — refuses to fall (1 HP)!',
    shieldReactionTitle: 'Incoming hit!',
    shieldReactionDetail: (attacker: string, total: number, ac: number) => `${attacker} hits you (${total} vs AC ${ac}) — Shield would turn it into a miss (AC ${ac + 5}).`,
    shieldCastLine: (attacker: string) => `🛡️ SHIELD! ${attacker}'s attack shatters against the arcane barrier (+5 AC until your next turn).`,
    dayWord: 'Day',
    // UI5 — textes de progression / overlays qui restaient en dur.
    levelUpLine: (lvl: number, hp: number) => `🎊 LEVEL UP! Level ${lvl}! Max HP: ${hp}!`,
    xpChronicleDesc: (amount: number, total: number) => `Gained ${amount} XP. Total now: ${total}.`,
    reasonCombatVictory: 'Combat victory',
    castHealedLabel: (spell: string, n: number) => `Cast: ${spell} (Healed: ${n} HP)`,
    consumesPotionLabel: (name: string, n: number) => `Potion: ${name} (+${n} HP)`,
    moraleCheckLabel: (name: string) => `${name} — morale check (Wisdom Save vs DC ${MORALE_DC})`,
    moraleFledLine: (name: string, total: number) => `${name} failed their morale check (WIS save ${total} vs DC ${MORALE_DC}) and FLEES the fight — alive!`,
    moraleHeldLine: (name: string, total: number) => `${name} passed their morale check (WIS save ${total} vs DC ${MORALE_DC}) and keeps fighting.`,
    attacksWith: 'attacks with',
    attackWord: 'Attack',
    saveNoun: 'Save',
    successWord: 'Success',
    failureWord: 'Failure',
    deathSaveRequired: 'Death save required. Roll a d20.',
    chronicleHeader: 'Chronicle',
    lvlAbbrev: 'Lvl',
  },
  fr: {
    ...SYSTEM_LINES.fr,
    railHandle: 'Largeur de la chronique — glisser, flèches, ou double-clic pour revenir',
    devModeOn: '🛠️ *[MODE DÉVELOPPEUR ACTIVÉ — le MJ obéit désormais à tes ordres directs. Retape IDDAD pour désactiver.]*',
    devModeOff: '🛠️ *[Mode développeur désactivé — le MJ reprend son arbitrage normal.]*',
    connectionRestored: '🔗 Connexion rétablie. Vous pouvez continuer.',
    connectionLostRetry: '⚠️ Connexion perdue. Tentative de reconnexion...',
    connectionLostNotSent: '⚠️ Connexion perdue. Message non envoyé. Tentative de reconnexion...',
    sendError: '❌ Erreur d\'envoi. Veuillez réessayer.',
    nothingToSave: 'Rien à sauvegarder !',
    gameSaved: '💾 Partie sauvegardée !',
    saveErrorConcurrency: 'Erreur de sauvegarde (concurrence ou données vides).',
    saveError: 'Erreur de sauvegarde !',
    sagaBegins: 'La saga commence…',
    hero: 'Héros',
    dm: 'MJ',
    talkToDM: 'Parler avec le DM...',
    reconnecting: 'Reconnexion en cours...',
    send: 'Envoyer',
    micActive: 'Micro actif',
    enableMic: 'Activer le micro',
    pendingReconnect: 'message(s) en attente de reconnexion',
    reconnectTitle: 'Connexion perdue',
    reconnectReassure: "Le Maître du Jeu revient. Rien n'est perdu — la partie est sauvegardée et vos dernières paroles sont en attente.",
    reconnectIn: 'Retour dans',
    reconnectSeconds: 's',
    reconnectLastTry: 'Dernière tentative en cours…',
    reconnectAttemptOf: 'Tentative {n} sur 3',
    generatingScene: 'Génération de la scène…',
    npcTurnInProgress: '🎲 Tour des PNJ en cours…',
    campaign: 'Campagne',
    codex: 'Codex',
    spellbook: 'Grimoire',
    connectionLostSimple: 'Impossible de se reconnecter au serveur.',
    reference: 'Référence',
    connected: 'Connecté',
    disconnected: 'Déconnecté',
    waiting: 'en attente',
    saving: 'Sauvegarde…',
    save: 'Sauver',
    saveFailed: '☁️ Non synchronisé',
    saveFailedTooltip: 'La sauvegarde cloud échoue — la progression récente risque de ne pas être conservée. Vérifiez votre connexion, puis cliquez sur Sauver.',
    music: 'Musique',
    shortRest: 'Repos court',
    longRest: 'Repos long',
    devBanner: '🛠️ Mode développeur — le MJ obéit',
    auditTitle: "Console d'audit (fenêtre séparée) — system prompts, Gemini, image, SFX, musique, combat",
    audit: '🔍 Audit',
    devTooltip: 'Mode développeur (le MJ obéit à tes ordres directs). Équivaut à taper IDDAD dans le chat.',
    dev: '🛠 Dév',
    on: 'ON',
    off: 'OFF',
    loadingCodex: 'Chargement du Codex…',
    hp: 'PV',
    levelWord: 'Niveau',
    combatEndedManually: '⚔️ Combat terminé manuellement.',
    appliedToAttack: 'appliqué à votre attaque',
    damage: 'Dégâts',
    hit: 'TOUCHÉ !',
    miss: 'MANQUÉ',
    critHit: 'COUP CRITIQUE',
    touched: 'touché',
    missed: 'manqué',
    attackLabel: 'Attaque',
    attackN: (n: number, max: number) => max > 1 ? `Attaque ${n}/${max}` : 'Attaque',
    frenzy: 'Frénésie',
    warPriest: 'Prêtre de guerre',
    offhandAttack: 'Attaque off-hand',
    shieldBash: 'Coup de bouclier',
    vs: 'vs',
    dodgeDesc: 'Défense active. Les attaques contre vous ont un désavantage.',
    test: 'test',
    saveWord: 'sauvegarde',
    saveSuccess: 'réussie',
    saveFail: 'ratée',
    checkSuccess: 'réussi',
    checkFail: 'raté',
    target: 'cible',
    takes: 'subit',
    enemyTargets: (npc: string, t: string) => `🎯 ${npc} cible ${t} (choix du MJ)`,
    ac: 'CA',
    potion: 'Potion',
    healing: 'soin',
    abilitySecondWindLabel: 'Second souffle',
    abilityLayOnHandsLabel: 'Imposition des mains',
    abilityBardicLabel: 'Inspiration bardique',
    abilityFlurryLabel: 'Déluge de coups',
    abilityPatientLabel: 'Défense patiente',
    abilitySmiteLabel: 'Châtiment divin',
    abilityRecklessLabel: 'Attaque téméraire',
    abilityStunningLabel: 'Frappe étourdissante',
    abilityStepWindLabel: 'Pas du vent',
    abilityTurnUndeadLabel: 'Renvoi des morts-vivants',
    abilityPactFocusLabel: 'Focalisation du pacte',
    abilityNaturalRecoveryLabel: 'Récupération naturelle',
    slotsRecovered: (n: number) => `${n} emplacement(s) de sort récupéré(s)`,
    martialArts: 'Arts martiaux',
    abilityDivineSenseLabel: 'Perception divine',
    abilitySacredWeaponLabel: 'Arme sacrée',
    abilityVowLabel: "Vœu d'inimitié",
    abilityWrathLabel: 'Courroux de la nature',
    abilityChallengeLabel: 'Défi du cavalier',
    abilityInterventionLabel: 'Intervention divine',
    abilityPrimevalLabel: 'Conscience primitive',
    abRage: '🔥 RAGE — +2 dégâts, résistance aux dégâts physiques (10 rounds)',
    abActionSurge: (n: number) => `⚡ Sursaut d'action — +${n} attaque(s) ce tour`,
    abBardic: (die: string, bonus: number) => `(${die}) — +${bonus} sur un prochain jet`,
    abPatient: "Esquive jusqu'à ton prochain tour",
    abFamiliar: (name: string, kind: string) => `🦉 ${name} (${kind}) harcèle l'ennemi — avantage sur ta prochaine attaque`,
    abLucky: (left: number) => `🍀 Chanceux — avantage sur ton prochain jet (${left} restant(s))`,
    abCunningHide: '🫥 Ruse — caché : avantage sur ta prochaine attaque',
    abCunningDash: "🏃 Ruse — Repli/Sprint : tu te repositionnes sans provoquer d'attaques",
    abGuidedStrike: "⚡ Frappe guidée — +10 sur ton prochain jet d'attaque",
    abFontOfMagic: '✨ Source de magie — emplacement de niveau 1 créé (2 pts de sorcellerie)',
    abManeuver: (die: string) => `🎲 Manœuvre — +${die} de dégâts sur tes attaques d'arme ce round`,
    abWildShape: (hp: number) => `🐻 Forme sauvage — ${hp} PV temporaires (10 rounds)`,
    abSmiteBurn: (lvl: number, dice: number) => `emplacement niv.${lvl} brûlé : +${dice}d8 radiants sur ta prochaine attaque réussie`,
    abReckless: "avantage sur tes attaques ce tour, mais tu t'exposes",
    abStunning: (dc: number) => `prochaine attaque réussie : sauvegarde de CON DD ${dc} ou étourdi`,
    abStepWind: 'Sprint + Désengagement',
    abPactFocus: 'avantage sur ta prochaine attaque de sort',
    abDivineSense: 'célestes, fiélons et morts-vivants à 18 m révélés',
    abSacredWeapon: (bonus: number) => `+${bonus} aux jets d'attaque (10 rounds)`,
    abVow: (foe: string) => `contre ${foe} — avantage sur tes attaques (10 rounds)`,
    abWrathFree: (foe: string) => `${foe} se libère des lianes`,
    abWrathHeld: (foe: string) => `${foe} est ENTRAVÉ par les lianes spectrales`,
    abChallenge: (foe: string) => `${foe} ne voit plus que toi`,
    abInterventionYes: '🌟 INTERVENTION DIVINE — ta divinité RÉPOND !',
    abInterventionNo: (roll: number, lvl: number) => `le ciel reste silencieux (${roll} > ${lvl})`,
    abPrimeval: 'présence des créatures surnaturelles à 1,5 km révélée',
    abQuickened: "ton prochain sort coûte l'action bonus",
    abHeightened: 'la prochaine sauvegarde ennemie se fera avec DÉSAVANTAGE',
    dcLabel: 'DD',
    abTurnDestroyed: (names: string) => `${names} DÉTRUIT(S)`,
    abTurnFled: (names: string) => `${names} fuient`,
    abTurnNone: 'aucun mort-vivant renvoyé',
    abTurnNoUndead: 'aucun mort-vivant présent',
    npcAllyTurn: (name: string) => `Tour de ${name} (allié) — le MJ le dirige`,
    npcPartyDown: 'Défaite — toute la partie est à terre.',
    npcCloseDistance: (name: string, from: string, to: string) => `${name} se rapproche (${from} → ${to}).`,
    bandFar: 'loin', bandNear: 'à distance', bandMelee: 'au contact',
    npcMissileCaught: ' — projectile ATTRAPÉ !',
    npcHeals: (caster: string, spell: string, target: string, hp: number) => `${caster} lance ${spell} sur ${target} — +${hp} PV`,
    gsTurnAdvanced: (who: string) => `Au tour de ${who}`,
    gsVictory: (xp: number) => `Victoire ! +${xp} XP`,
    gsEffectsExpired: (names: string) => `Effet(s) dissipé(s) : ${names}`,
    gsEffectsExpiredTime: (names: string) => `Effet(s) dissipé(s) avec le temps : ${names}`,
    gsCombatResumed: "Combat repris — c'est à toi de jouer.",
    gsConcentrationHeld: 'Concentration maintenue',
    gsPotionDrunk: (name: string, healing: number) => `${name} consommé — +${healing} PV`,
    gsItemUsed: (name: string) => `${name} utilisé`,
    gsStoryModeOn: 'Mode histoire activé — potions et sorts de soin rendent leur maximum',
    gsStoryModeOff: 'Mode histoire désactivé — les soins redeviennent des jets',
    gsRerollLabelIndomitable: 'Inflexible',
    gsRerollLabelInspiration: 'Inspiration brûlée',
    gsReroll: (label: string, total: number, dc: number, ok: boolean) =>
        `🎲 ${label} — relance : ${total} vs DD ${dc} (${ok ? 'réussite' : 'échec'})`,
    aoeDamageRoll: 'dégâts de zone',
    hazardDamage: (hazard: string, amount: number, type: string) => `${hazard} — ${amount} dégâts ${type}`,
    paNoAttackLeft: "Plus d'attaque ce tour — terminez votre tour ou utilisez une action bonus.",
    paAdvance: (who: string, target: string, from: string, to: string, melee: boolean) =>
        `${who} se rapproche de ${target} (${from} → ${to})${melee ? ' — au contact, frappe possible' : ''}.`,
    paDarkBlessing: (hp: number) => `🔥 Bénédiction du Ténébreux — ${hp} PV temporaires`,
    paBonusUsed: 'Action bonus déjà utilisée ce tour.',
    paMainFirst: "Attaque d'abord avec ton arme principale — l'attaque bonus vient APRÈS l'action Attaque.",
    paPotionBuff: (name: string, label: string) => `${name} — ${label} pendant 1 h`,
    paMainUsedFor: (label: string) => `Action principale déjà utilisée ce tour — « ${label} » impossible.`,
    paBonusUsedFor: (label: string) => `Action bonus déjà utilisée ce tour — « ${label} » impossible.`,
    paReactionUsedFor: (label: string) => `Réaction déjà utilisée ce tour — « ${label} » impossible.`,
    abilityQuickenedLabel: 'Sort accéléré',
    abilityHeightenedLabel: 'Sort intensifié',
    abilityWholenessLabel: 'Plénitude du corps',
    rerollIndomitable: 'Relancer avec Inflexible',
    reactionUncanny: 'Esquive instinctive — dégâts divisés par deux',
    reactionDeflect: (n: number) => `Déviation de projectiles — ${n} dégâts déviés`,
    relentlessLine: 'RAGE IMPLACABLE — refuse de tomber (1 PV) !',
    shieldReactionTitle: 'Coup imminent !',
    shieldReactionDetail: (attacker: string, total: number, ac: number) => `${attacker} te touche (${total} vs CA ${ac}) — Bouclier transformerait le coup en échec (CA ${ac + 5}).`,
    shieldCastLine: (attacker: string) => `🛡️ BOUCLIER ! L'attaque de ${attacker} se brise sur la barrière arcanique (+5 CA jusqu'à ton prochain tour).`,
    dayWord: 'Jour',
    // UI5 — textes de progression / overlays qui restaient en dur.
    levelUpLine: (lvl: number, hp: number) => `🎊 NIVEAU SUPÉRIEUR ! Niveau ${lvl} ! PV max : ${hp} !`,
    xpChronicleDesc: (amount: number, total: number) => `${amount} XP gagnés. Total : ${total}.`,
    reasonCombatVictory: 'Victoire au combat',
    castHealedLabel: (spell: string, n: number) => `Sort : ${spell} (+${n} PV)`,
    consumesPotionLabel: (name: string, n: number) => `Potion : ${name} (+${n} PV)`,
    moraleCheckLabel: (name: string) => `${name} — test de moral (sauvegarde de Sagesse vs DD ${MORALE_DC})`,
    moraleFledLine: (name: string, total: number) => `${name} rate son test de moral (sauvegarde SAG ${total} vs DD ${MORALE_DC}) et S'ENFUIT du combat — vivant !`,
    moraleHeldLine: (name: string, total: number) => `${name} réussit son test de moral (sauvegarde SAG ${total} vs DD ${MORALE_DC}) et continue de se battre.`,
    attacksWith: 'attaque avec',
    attackWord: 'Attaque',
    saveNoun: 'Sauvegarde',
    successWord: 'Réussite',
    failureWord: 'Échec',
    deathSaveRequired: 'Jet de mort requis. Lance un d20.',
    chronicleHeader: 'Chronique',
    lvlAbbrev: 'Niv',
  },
} as const;
