/**
 * Les textes (fr / en) des ecrans de ce dossier, une table par composant.
 *
 * Rassembles ici le 2026-08-25 (R8 du rangement) : chaque table vivait en
 * tete de son composant sous le nom TRANS ; le composant l'importe
 * desormais sous ce meme alias, ses usages n'ont pas change. Contenu
 * inchange.
 */

// ── CharacterSheet ──
export const CHARACTER_SHEET_TEXTS = {
  en: {
    stepIdentity: 'Identity', stepBuild: 'Build', stepGear: 'Equipment', stepSpells: 'Spells', stepStory: 'Story', stepReview: 'Recap',
    steps: 'Creation steps', vitals: 'Vitals',
    fullClassSheet: 'Full class sheet', closeSheet: 'Close',
    builderHint: 'Build the sheet, then give the DM enough identity hooks to write a personal campaign opening.',
    name: 'Name', class: 'Class', race: 'Race', background: 'Background', style: 'Style', deity: 'Deity', none: 'None',
    characterName: 'Character name', namePlaceholder: 'Give your hero a name…',
    sex: 'Sex', male: 'Male', female: 'Female',
    classHint: '— hit dice, saving throws, abilities',
    mandatoryLvl1: '— mandatory at level 1',
    startingAbilities: '— starting abilities',
    raceHint: '— ability bonuses and traits',
    subraceOf: (r: string) => `Subrace of ${r}`, mandatory: '— mandatory',
    draconicAncestry: 'Draconic Ancestry', ancestryHint: '— sets your breath weapon & damage resistance',
    dmgType: { fire: 'fire', cold: 'cold', lightning: 'lightning', acid: 'acid', poison: 'poison' } as Record<string, string>,
    traits: '— traits', proficienciesLabel: 'Proficiencies:', resistancesLabel: 'Resistances:', darkvision: 'Darkvision',
    bgHint: '— skills and social trait', skillsAbbr: 'Skills:',
    fightingStyle: 'Fighting Style', deityHint: '— optional',
    deityGood: 'Good', deityNeutral: 'Neutral', deityEvil: 'Evil', domainLabel: 'Domain',
    lvl: 'lvl.',
    characterBible: 'Character Bible',
    bibleHint: "These fields feed the DM, the campaign opening, and the cinematic. Ideal / Bond / Flaw + a secret = the SRD pillars.",
    quickArchetype: 'Quick archetype', quickArchetypeHint: '— pre-fills the pillars, then edit freely',
    appearance: 'Appearance', desire: 'Desire', personality: 'Personality', fearWeakness: 'Fear / Weakness',
    bondLien: 'Bond', woundRegret: 'Wound / Regret', secret: 'Secret', secretHint: '— private, DM-only',
    appearancePh: 'Armor, scars, colors, posture, symbol, weapon silhouette...',
    desirePh: 'What does the hero want badly enough to risk death?',
    personalityPh: 'How do they speak, decide, threaten, comfort, joke?',
    fearPh: 'What can the villain exploit?',
    bondPh: 'A person, oath, place, mentor, family, rival, or debt.',
    woundPh: 'The old failure, loss, exile, betrayal, or shame.',
    secretPh: 'A secret the DM can reveal or exploit: a hidden betrayal, a true identity, a pact, a shameful debt...',
    backstory: 'Backstory',
    backstoryPh: "Write the short version of the hero's past. The DM will use it as personal campaign fuel.",
    dmHooks: 'DM Hooks',
    dmHooksPh: 'One hook per line:\nA missing sibling\nA cursed rank insignia\nA debt to a temple',
    ideal: 'Ideal', idealPh: 'Justice, freedom...', flaw: 'Flaw', flawPh: 'Pride, mercy, rage...',
    cinematicTone: 'Cinematic Tone',
    abilityScores: 'Ability Scores', pointsRemaining: 'Points Remaining', base: 'base',
    pointMode: 'Difficulty', modeNormal: 'Normal', modeStory: 'Story',
    modeNormalHint: 'Standard 27 points', modeStoryHint: 'Generous 37 points',
    armorClass: 'Armor Class', acTooltip: '10 + DEX Mod', hitPoints: 'Hit Points', hitDie: 'Hit Die',
    startingEquipment: 'Starting Equipment', resetKit: 'Reset Kit',
    item: 'Item', qty: 'Qty', wgt: 'Wgt', noEquipment: 'No equipment selected',
    skills: 'Skills', atChoice: 'at choice', passivePerception: 'Passive Perception',
    expertiseHint: (cur: number, max: number) => `★ Expertise (${cur}/${max}) — click the star of a proficient skill to double the proficiency.`,
    grantedByBgRace: 'Granted by background/race', classSkillChoice: 'Class skill (at choice)', outOfClassList: 'Outside your class list',
    expertiseTitle: 'Expertise (double proficiency)',
    gearTitle: 'Starting equipment', gold: 'gp',
    gearIntro1: 'You receive your class', gearIntroPack: 'pack', gearIntro2: '(focus, explorer pack…)', gearIntroFree: 'for free', gearIntro3: ', plus a',
    gearIntroDefaultKit: 'default kit', gearIntro4: 'already equipped. With your starting gold (your class SRD wealth + background bonus),',
    gearIntroBuy: 'buy', gearIntroSell: 'resell', gearIntroEquip: 'equip', gearIntro5: 'your gear as you see fit.',
    yourEquipment: 'Your equipment', nothingEquippable: 'Nothing equippable yet — buy a weapon or armor below.',
    equipped: 'Equipped', equip: 'Equip', resellTitle: 'Resell (recover gold)',
    packIncluded: 'Pack (included)',
    shop: 'Shop', simpleWeapons: 'Simple weapons', martialWeapons: 'Martial weapons', armors: 'Armors',
    twoHanded: 'two-handed', buy: 'Buy', stealthDisadv: '⚠ Stealth disadv.',
    casterSetup: 'Caster Setup',
    casterIntro: (cantrips: number, spells: number, mode: string) => `Choose ${cantrips} cantrip(s) and ${spells} ${mode} level 1 spell(s).`,
    prepared: 'prepared', known: 'known',
    noCasterSetup: 'This class has no spellcasting setup at level 1.',
    noCasterClass: (cls: string) => `${cls} starts as a martial/non-caster in the current rules setup. Continue to Story.`,
    castingAbility: 'Casting Ability', focus: 'Focus', spellSlots: 'Spell Slots', cantripsOnly: 'Cantrips only',
    focusHint: "The object that channels your spells. Rename it freely for roleplay (an obsidian orb, your mother's ring…) — the DM will use it.",
    cantrips: 'Cantrips', level1Spells: 'Level 1 Spells', concentration: 'concentration',
    heroBrief: 'Hero Brief', identity: 'Identity', unnamedHero: 'Unnamed Hero', deityColon: 'Deity:',
    mechanics: 'Mechanics', weapon: 'Weapon:', unarmed: 'Unarmed', pointBuy: 'Point buy:', complete: 'complete', remaining: 'remaining',
    cinematic: 'Cinematic', readyForIntro: 'Ready for personal intro', appearanceDesireRequired: 'Appearance and desire required',
    magic: 'Magic', chooseCantrips: 'Choose cantrips before starting.', preparedSpells: 'Prepared Spells', knownSpells: 'Known Spells',
    chooseLvl1: 'Choose level 1 spells before starting.',
    appearanceMissing: 'Missing. The intro image will be generic until this is filled.', coreDesire: 'Core Desire',
    desireMissing: 'Missing. The campaign hook needs a personal goal.',
    back: 'Back', continue: 'Continue', nameRequired: 'Name required',
    spendPoints: (n: number) => `Spend your remaining points (${n})`,
    chooseYour: (l: string) => `Choose your ${l}`, archetype: 'archetype',
    addAppearanceDesire: 'Add appearance + desire', chooseStartingSpells: 'Choose your starting spells', toAdventure: "To adventure!",
    hitDiceLabel: 'Hit Die', primaryAbility: 'Primary Ability', savingThrows: 'Saving Throws', proficiencies: 'Proficiencies',
    classFeatures: 'Class Features', xpPerLevel: 'XP per Level', levelAbbr: 'Lvl',
  },
  fr: {
    stepIdentity: 'Identité', stepBuild: 'Profil', stepGear: 'Équipement', stepSpells: 'Sorts', stepStory: 'Histoire', stepReview: 'Récap',
    steps: 'Étapes de création', vitals: 'Constantes',
    fullClassSheet: 'Fiche complète', closeSheet: 'Fermer',
    builderHint: "Construis la fiche, puis donne au MJ assez d'accroches d'identité pour écrire une ouverture de campagne personnelle.",
    name: 'Nom', class: 'Classe', race: 'Race', background: 'Historique', style: 'Style', deity: 'Divinité', none: 'Aucune',
    characterName: 'Nom du personnage', namePlaceholder: 'Donne un nom à ton héros…',
    sex: 'Sexe', male: 'Homme', female: 'Femme',
    classHint: '— dés de vie, sauvegardes, capacités',
    mandatoryLvl1: '— obligatoire au niveau 1',
    startingAbilities: '— aptitudes de départ',
    raceHint: '— bonus de caractéristiques et traits',
    subraceOf: (r: string) => `Sous-race de ${r}`, mandatory: '— obligatoire',
    draconicAncestry: 'Ascendance draconique', ancestryHint: '— définit ton souffle et ta résistance',
    dmgType: { fire: 'feu', cold: 'froid', lightning: 'foudre', acid: 'acide', poison: 'poison' } as Record<string, string>,
    traits: '— traits', proficienciesLabel: 'Maîtrises :', resistancesLabel: 'Résistances :', darkvision: 'Vision dans le noir',
    bgHint: '— compétences et trait social', skillsAbbr: 'Comp. :',
    fightingStyle: 'Style de combat', deityHint: '— optionnel',
    deityGood: 'Bien', deityNeutral: 'Neutre', deityEvil: 'Mal', domainLabel: 'Domaine',
    lvl: 'niv.',
    characterBible: 'Bible du personnage',
    bibleHint: "Ces champs nourrissent le MJ, l'ouverture de campagne et la cinématique. Idéal / Lien / Défaut + un secret = les piliers SRD.",
    quickArchetype: 'Archétype rapide', quickArchetypeHint: '— pré-remplit les piliers, puis édite librement',
    appearance: 'Apparence', desire: 'Désir', personality: 'Personnalité', fearWeakness: 'Peur / Faiblesse',
    bondLien: 'Lien', woundRegret: 'Blessure / Regret', secret: 'Secret', secretHint: '— privé, connu du seul MJ',
    appearancePh: 'Armure, cicatrices, couleurs, posture, symbole, silhouette d\'arme...',
    desirePh: 'Que veut le héros au point de risquer la mort ?',
    personalityPh: 'Comment parle-t-il, décide-t-il, menace-t-il, réconforte-t-il, plaisante-t-il ?',
    fearPh: 'Que peut exploiter le méchant ?',
    bondPh: 'Une personne, un serment, un lieu, un mentor, une famille, un rival ou une dette.',
    woundPh: "L'ancien échec, la perte, l'exil, la trahison ou la honte.",
    secretPh: "Un secret que le MJ pourra révéler ou exploiter : une trahison cachée, une vraie identité, un pacte, une dette honteuse...",
    backstory: 'Histoire personnelle',
    backstoryPh: "Écris la version courte du passé du héros. Le MJ s'en servira comme carburant personnel de campagne.",
    dmHooks: 'Accroches MJ',
    dmHooksPh: 'Une accroche par ligne :\nUn frère ou une sœur disparu(e)\nUn insigne de rang maudit\nUne dette envers un temple',
    ideal: 'Idéal', idealPh: 'Justice, liberté...', flaw: 'Défaut', flawPh: 'Orgueil, pitié, rage...',
    cinematicTone: 'Ton cinématique',
    abilityScores: 'Caractéristiques', pointsRemaining: 'Points restants', base: 'base',
    pointMode: 'Difficulté', modeNormal: 'Normal', modeStory: 'Histoire',
    modeNormalHint: '27 points standard', modeStoryHint: '37 points généreux',
    armorClass: 'Classe d\'armure', acTooltip: '10 + mod. DEX', hitPoints: 'Points de vie', hitDie: 'Dé de vie',
    startingEquipment: 'Équipement de départ', resetKit: 'Réinit. kit',
    item: 'Objet', qty: 'Qté', wgt: 'Poids', noEquipment: 'Aucun équipement sélectionné',
    skills: 'Compétences', atChoice: 'au choix', passivePerception: 'Perception passive',
    expertiseHint: (cur: number, max: number) => `★ Expertise (${cur}/${max}) — clique l'étoile d'une compétence maîtrisée pour doubler la maîtrise.`,
    grantedByBgRace: 'Accordée par le background/la race', classSkillChoice: 'Compétence de classe au choix', outOfClassList: 'Hors de la liste de ta classe',
    expertiseTitle: 'Expertise (double maîtrise)',
    gearTitle: 'Équipement de départ', gold: 'po',
    gearIntro1: 'Tu reçois ton', gearIntroPack: 'paquetage', gearIntro2: "de classe (focalisateur, sac d'exploration…)", gearIntroFree: 'gratuitement', gearIntro3: ', plus un',
    gearIntroDefaultKit: 'kit par défaut', gearIntro4: "déjà équipé. Avec ton or de départ (richesse SRD de ta classe + bonus de background),",
    gearIntroBuy: 'achète', gearIntroSell: 'revends', gearIntroEquip: 'équipe', gearIntro5: "ton matériel comme tu l'entends.",
    yourEquipment: 'Ton équipement', nothingEquippable: "Rien d'équipable pour l'instant — achète une arme ou une armure ci-dessous.",
    equipped: 'Équipé', equip: 'Équiper', resellTitle: "Revendre (récupère l'or)",
    packIncluded: 'Paquetage (inclus)',
    shop: 'Boutique', simpleWeapons: 'Armes courantes', martialWeapons: 'Armes de guerre', armors: 'Armures',
    twoHanded: 'à 2 mains', buy: 'Acheter', stealthDisadv: '⚠ Discrétion désav.',
    casterSetup: 'Préparation des sorts',
    casterIntro: (cantrips: number, spells: number, mode: string) => `Choisis ${cantrips} sort(s) mineur(s) et ${spells} sort(s) de niveau 1 ${mode}.`,
    prepared: 'préparé(s)', known: 'connu(s)',
    noCasterSetup: 'Cette classe ne lance pas de sorts au niveau 1.',
    noCasterClass: (cls: string) => `${cls} débute comme classe martiale/non-lanceuse de sorts dans les règles actuelles. Continue vers Histoire.`,
    castingAbility: 'Caractéristique d\'incantation', focus: 'Focaliseur', spellSlots: 'Emplacements de sorts', cantripsOnly: 'Sorts mineurs uniquement',
    focusHint: "L'objet qui canalise tes sorts. Renomme-le librement pour le roleplay (un orbe d'obsidienne, la bague de ta mère…) — le MJ s'en servira.",
    cantrips: 'Sorts mineurs', level1Spells: 'Sorts de niveau 1', concentration: 'concentration',
    heroBrief: 'Fiche du héros', identity: 'Identité', unnamedHero: 'Héros sans nom', deityColon: 'Divinité :',
    mechanics: 'Mécaniques', weapon: 'Arme :', unarmed: 'Mains nues', pointBuy: 'Achat de points :', complete: 'complet', remaining: 'restants',
    cinematic: 'Cinématique', readyForIntro: 'Prêt pour une intro personnelle', appearanceDesireRequired: 'Apparence et désir requis',
    magic: 'Magie', chooseCantrips: 'Choisis tes sorts mineurs avant de commencer.', preparedSpells: 'Sorts préparés', knownSpells: 'Sorts connus',
    chooseLvl1: 'Choisis tes sorts de niveau 1 avant de commencer.',
    appearanceMissing: "Manquant. L'image d'intro restera générique tant que ce champ est vide.", coreDesire: 'Désir central',
    desireMissing: "Manquant. L'accroche de campagne a besoin d'un objectif personnel.",
    back: 'Retour', continue: 'Continuer', nameRequired: 'Nom requis',
    spendPoints: (n: number) => `Dépense tes points restants (${n})`,
    chooseYour: (l: string) => `Choisis ton ${l}`, archetype: 'archétype',
    addAppearanceDesire: 'Ajoute apparence + désir', chooseStartingSpells: 'Choisis tes sorts de départ', toAdventure: "À l'aventure !",
    hitDiceLabel: 'Dé de Vie', primaryAbility: 'Caractéristique Principale', savingThrows: 'Jets de Sauvegarde', proficiencies: 'Maîtrises',
    classFeatures: 'Capacités de Classe', xpPerLevel: 'XP par Niveau', levelAbbr: 'Niv',
  },
} as const;

// ── HeroPortraitForge ──
export const HERO_PORTRAIT_FORGE_TEXTS = {
    en: {
        title: 'Hero portrait',
        hint: 'Built from everything you wrote above — identity, appearance, weapon, temperament. The portrait you keep becomes your hero in every scene the game illustrates.',
        generate: 'Forge a portrait',
        again: 'Try another',
        attemptsLeft: (n: number) => `${n} attempt${n > 1 ? 's' : ''} left`,
        noAttempts: 'No attempts left — the kept portrait is final.',
        needAppearance: 'Fill in Appearance first: without it the portrait will be generic.',
        keep: 'Keep this one',
        kept: 'Kept',
        working: 'Painting…',
        failed: 'Generation failed — nothing was deducted. Check that the image server or key is reachable, then try again.',
        imagesOff: 'Image generation is disabled in the Settings — enable “Scene images” and “Generated portraits” to forge.',
    },
    fr: {
        title: 'Portrait du héros',
        hint: "Construit à partir de tout ce que tu as écrit ci-dessus — identité, apparence, arme, tempérament. Le portrait que tu gardes devient ton héros dans chaque scène illustrée par le jeu.",
        generate: 'Forger un portrait',
        again: 'En essayer un autre',
        attemptsLeft: (n: number) => `${n} essai${n > 1 ? 's' : ''} restant${n > 1 ? 's' : ''}`,
        noAttempts: 'Plus d’essai — le portrait gardé est définitif.',
        needAppearance: "Renseigne d'abord l'Apparence : sans elle le portrait sera générique.",
        keep: 'Garder celui-ci',
        kept: 'Gardé',
        working: 'Peinture en cours…',
        failed: "Échec de la génération — aucun essai décompté. Vérifie que le serveur d'images ou la clé répond, puis réessaie.",
        imagesOff: "La génération d'images est coupée dans les Réglages — active « Images de scène » et « Portraits générés » pour forger.",
    },
} as const;

// ── LoadGameMenu ──
export const LOAD_GAME_MENU_TEXTS = {
    en: {
        confirmDelete: "Delete this save?",
        failedToLoad: "Failed to load saves",
        title: "📜 Load a Game",
        subtitle: "Resume where you left off",
        loadingSaves: "Loading saves...",
        retry: "Retry",
        noSaves: "No saves found",
        startNew: "Start a new adventure!",
        level: "Lv.",
        continue: "Continue",
        close: "Close",
        justNow: "Just now",
        minAgo: (n: number) => `${n} min ago`,
        hoursAgo: (n: number) => `${n}h ago`,
        daysAgo: (n: number) => `${n} day${n > 1 ? 's' : ''} ago`,
        locale: 'en-US',
    },
    fr: {
        confirmDelete: "Supprimer cette sauvegarde ?",
        failedToLoad: "Échec du chargement des sauvegardes",
        title: "📜 Charger une Partie",
        subtitle: "Reprendre là où vous vous êtes arrêté",
        loadingSaves: "Chargement des sauvegardes...",
        retry: "Réessayer",
        noSaves: "Aucune sauvegarde trouvée",
        startNew: "Commencez une nouvelle aventure !",
        level: "Nv.",
        continue: "Continuer",
        close: "Fermer",
        justNow: "À l'instant",
        minAgo: (n: number) => `Il y a ${n} min`,
        hoursAgo: (n: number) => `Il y a ${n}h`,
        daysAgo: (n: number) => `Il y a ${n} jour${n > 1 ? 's' : ''}`,
        locale: 'fr-FR',
    },
} as const;

// ── SignInGate ────────────────────────────────────────────────────────────
// La fenêtre de connexion qui s'ouvre au-dessus du jeu quand un visiteur sans
// compte tente de charger une partie ou de lancer son aventure.
export const SIGN_IN_GATE_TEXTS = {
    fr: {
        title: 'Connectez-vous pour continuer',
        reasonLaunch: 'Votre héros est prêt. Créez un compte — gratuit, en dix secondes — pour lancer l\u2019aventure et la retrouver plus tard.',
        reasonLoad: 'Les parties sauvegardées appartiennent à un compte. Connectez-vous pour retrouver les vôtres.',
        characterKept: 'Votre personnage est conservé : il vous suit dans votre nouveau compte.',
        emailPlaceholder: 'E-mail',
        passwordPlaceholder: 'Mot de passe',
        login: 'Connexion',
        register: 'Créer un compte',
        working: 'Un instant…',
        orContinue: 'Ou continuez avec',
        signInGoogle: 'Continuer avec Google',
        close: 'Fermer',
        emailTaken: 'Cette adresse a déjà un compte. Utilisez « Connexion » pour le retrouver.',
        badCredentials: 'E-mail ou mot de passe incorrect.',
        weakPassword: 'Mot de passe trop court : six caractères au minimum.',
        popupClosed: 'La fenêtre Google a été fermée avant la fin.',
        failed: 'La connexion a échoué. Réessayez.',
    },
    en: {
        title: 'Sign in to continue',
        reasonLaunch: 'Your hero is ready. Create a free account — it takes ten seconds — to start the adventure and find it again later.',
        reasonLoad: 'Saved games belong to an account. Sign in to find yours.',
        characterKept: 'Your character is kept: it follows you into your new account.',
        emailPlaceholder: 'Email',
        passwordPlaceholder: 'Password',
        login: 'Sign in',
        register: 'Create account',
        working: 'One moment…',
        orContinue: 'Or continue with',
        signInGoogle: 'Continue with Google',
        close: 'Close',
        emailTaken: 'That address already has an account. Use "Sign in" to reach it.',
        badCredentials: 'Wrong email or password.',
        weakPassword: 'Password too short: six characters minimum.',
        popupClosed: 'The Google window was closed before finishing.',
        failed: 'Sign-in failed. Please try again.',
    },
} as const;
