/**
 * Les textes (fr / en) des ecrans de ce dossier, une table par composant.
 *
 * Rassembles ici le 2026-08-25 (R8 du rangement) : chaque table vivait en
 * tete de son composant sous le nom TRANS ; le composant l'importe
 * desormais sous ce meme alias, ses usages n'ont pas change. Contenu
 * inchange.
 */

// ── CharacterCreationView ──
export const CHARACTER_CREATION_VIEW_TEXTS = {
    en: {
        multiplayerDisabled: "Multiplayer is disabled until real-time state sync is implemented.",
        personalizationError: "Error while personalizing the campaign.",
        unknownGenError: "Unknown error while generating the adventure.",
        manifestError: "Unable to generate the adventure manifest.",
        enteringArena: "Entering the Arena...",
        stepScars: "Reading your hero's scars...",
        stepHooks: "Binding personal hooks to the world...",
        stepVillain: "Mirroring the villain to your desire...",
        stepAllies: "Choosing allies, secrets, and threats...",
        stepCinematic: "Preparing the opening cinematic...",
        stepInscribing: "Inscribing the saga...",
        genErrorTitle: "⚠️ Generation Error",
        back: "← Back",
        adventureManifest: "Adventure Manifest",
        initSeeds: "Initializing world seeds...",
        checkingAlignment: "Checking alignment with",
        preparingSave: "Preparing save state...",
        readyingDice: "Readying the Dice of Fate...",
        backLobby: "Back",
        skipVideo: "Skip",
    },
    fr: {
        multiplayerDisabled: "Le multijoueur est désactivé jusqu'à l'implémentation de la synchronisation d'état en temps réel.",
        personalizationError: "Erreur lors de la personnalisation de la campagne.",
        unknownGenError: "Erreur inconnue lors de la génération de l'aventure.",
        manifestError: "Impossible de générer le manifeste d'aventure.",
        enteringArena: "Entrée dans l'Arène...",
        stepScars: "Lecture des cicatrices de votre héros...",
        stepHooks: "Liaison de vos enjeux personnels au monde...",
        stepVillain: "Reflet du vilain dans votre désir...",
        stepAllies: "Choix des alliés, des secrets et des menaces...",
        stepCinematic: "Préparation de la cinématique d'ouverture...",
        stepInscribing: "Inscription de la saga...",
        genErrorTitle: "⚠️ Erreur de Génération",
        back: "← Retour",
        adventureManifest: "Manifeste d'Aventure",
        initSeeds: "Initialisation des graines du monde...",
        checkingAlignment: "Vérification de l'alignement avec",
        preparingSave: "Préparation de la sauvegarde...",
        readyingDice: "Préparation des Dés du Destin...",
        backLobby: "Retour",
        skipVideo: "Passer",
    },
} as const;

// ── LobbyView ──
export const LOBBY_VIEW_TEXTS = {
    en: {
        back: "Back",
        selectAdventure: "Select Your Adventure",
        shareCode: "Share Session Code",
        inviteFriends: "Invite your friends to join your adventure!",
        selected: "Selected",
        continueExisting: "Continue Existing Adventure",
        createCharacter: "Create Character",
        saveCorrupted: "Save data is corrupted. Please create a new character.",
        noSaves: "No saved games found. Create a new hero!",
        loadFailed: "Failed to load: ",
        authored: "Hand-written campaign",
        generated: "Improvised by the DM",
        levels: "Levels",
        chapters: "chapters",
        acts: "acts",
        sessions: "sessions",
        difficulty: "Demand",
        gentle: "Forgiving",
        standard: "Standard",
        harsh: "Punishing",
        pickFirst: "Pick an adventure first",
        sectionAuthored: "Original campaigns",
        sectionAuthoredSub: "Written chapter by chapter for this game. The DM follows a real plot — named characters who remember you, planted secrets, an ending that was decided in advance. It does not make it up as it goes.",
        sectionClassics: "The great classics",
        sectionClassicsSub: "The archetypes of the genre: the haunted mine, the city of intrigue, the endless dungeon. Here the DM receives a premise and builds the story around your choices — no two runs are alike.",
    },
    fr: {
        back: "Retour",
        selectAdventure: "Choisissez Votre Aventure",
        shareCode: "Partager le Code de Session",
        inviteFriends: "Invitez vos amis à rejoindre votre aventure !",
        selected: "Sélectionné",
        continueExisting: "Continuer une Aventure Existante",
        createCharacter: "Créer un Personnage",
        saveCorrupted: "Les données de sauvegarde sont corrompues. Veuillez créer un nouveau personnage.",
        noSaves: "Aucune partie sauvegardée trouvée. Créez un nouveau héros !",
        loadFailed: "Échec du chargement : ",
        authored: "Campagne d'auteur",
        generated: "Improvisée par le MJ",
        levels: "Niveaux",
        chapters: "chapitres",
        acts: "actes",
        sessions: "séances",
        difficulty: "Exigence",
        gentle: "Indulgente",
        standard: "Standard",
        harsh: "Impitoyable",
        pickFirst: "Choisissez d'abord une aventure",
        sectionAuthored: "Campagnes d'auteur",
        sectionAuthoredSub: "Écrites chapitre par chapitre pour ce jeu. Le MJ suit une vraie trame — des personnages nommés qui se souviennent de vous, des secrets posés à l'avance, une fin déjà décidée. Il n'invente pas au fil de la partie.",
        sectionClassics: "Les grands classiques",
        sectionClassicsSub: "Les archétypes du genre : la mine hantée, la cité en intrigue, le donjon sans fin. Ici le MJ reçoit une prémisse et bâtit l'histoire autour de vos choix — deux parties ne se ressemblent jamais.",
    },
} as const;

// ── LoginView ──
export const LOGIN_VIEW_TEXTS = {
    en: {
        tagline: "The last place where we still play like we used to.",
        kicker: "A DUNGEON MASTER THAT SPEAKS, AND LISTENS",
        pitch: "A tabletop role-playing game with a dungeon master who runs the table live: he describes the room out loud, gives every character its own voice, hears what you answer, and remembers all of it — your choices, your oaths, and the guard you knocked out in chapter 2.",
        emailPlaceholder: "Email",
        passwordPlaceholder: "Password",
        login: "Login",
        register: "Register",
        orContinue: "Or continue with",
        signInGoogle: "Sign in with Google",
        loginFailed: "Login failed: ",
        signupFailed: "Signup failed: ",
        googleLoginFailed: "Google Login failed: ",
        guestLoginFailed: "Guest login failed: ",
        playAsGuest: "Play without an account",
        guestHint: "A guest table is tied to this browser only: clear your data or change device and it is gone. Sign in later to keep it.",
        authFailed: "Authentication failed",
        basement: "Doors close. Screens win. Down here, the table is still set.",
        googleBlocked: (domain: string, url: string) => `Google login is blocked by Firebase because "${domain}" is not in Authentication > Settings > Authorized domains. Add "${domain}" there, or open the app from localhost instead: ${url}`,
    },
    fr: {
        tagline: "Le dernier endroit où l'on joue encore comme avant.",
        kicker: "UN MAÎTRE DU JEU QUI PARLE, ET QUI ÉCOUTE",
        pitch: "Un jeu de rôle sur table avec un maître du jeu qui mène la partie en direct : il décrit la salle à voix haute, prête sa voix à chaque personnage, entend ce que vous répondez, et se souvient de tout — vos choix, vos serments, et le garde que vous avez assommé au chapitre 2.",
        emailPlaceholder: "E-mail",
        passwordPlaceholder: "Mot de passe",
        login: "Connexion",
        register: "S'inscrire",
        orContinue: "Ou continuez avec",
        signInGoogle: "Se connecter avec Google",
        loginFailed: "Échec de la connexion : ",
        signupFailed: "Échec de l'inscription : ",
        googleLoginFailed: "Échec de la connexion Google : ",
        guestLoginFailed: "Échec de la connexion invité : ",
        playAsGuest: "Jouer sans compte",
        guestHint: "Une table invitée n'existe que dans ce navigateur : effacez vos données ou changez d'appareil et elle disparaît. Connectez-vous plus tard pour la garder.",
        authFailed: "Échec de l'authentification",
        basement: "Les portes ferment. Les écrans gagnent. En bas, la table est encore mise.",
        googleBlocked: (domain: string, url: string) => `La connexion Google est bloquée par Firebase car "${domain}" ne figure pas dans Authentication > Settings > Authorized domains. Ajoutez-y "${domain}", ou ouvrez l'application depuis localhost à la place : ${url}`,
    },
} as const;
