/**
 * Les textes (fr / en) des ecrans de ce dossier, une table par composant.
 *
 * Rassembles ici le 2026-08-25 (R8 du rangement) : chaque table vivait en
 * tete de son composant sous le nom TRANS ; le composant l'importe
 * desormais sous ce meme alias, ses usages n'ont pas change. Contenu
 * inchange.
 */

// ── CombatActionsPanel ──
export const COMBAT_ACTIONS_PANEL_TEXTS = {
    en: {
        offhand: (name: string) => `Off-hand: ${name}`,
        frenzy: (name: string) => `Frenzy: ${name}`,
        warPriest: (name: string, uses: number) => `War Priest: ${name} (${uses})`,
        waitingTurnOf: (name: string) => `Waiting — ${name}'s turn…`,
        waitingUpdate: 'Waiting for the combat update…',
        incapacitatedBanner: (cond: string) => `${cond} — you cannot act this turn. Your turn will pass automatically.`,
        dyingBanner: 'Unconscious (0 HP) — death saving throws in progress. You cannot act.',
        combatActionsHeader: '⚔️ Combat Actions (Your Turn)',
        actionAvailable: 'Action Available',
        attack: 'Attack',
        spells: 'Spells',
        items: 'Items',
        dodge: 'Dodge',
        equippedWeapon: 'Equipped Weapon',
        noWeaponEquipped: 'No weapon equipped! Open the inventory to equip one.',
        damage: 'damage',
        target: 'Target',
        noEnemyTarget: 'No enemy target in combat.',
        hpLabel: 'HP',
        acLabel: 'AC',
        resolving: 'Resolving…',
        attackBtn: 'Attack ⚔️',
        bonusNeedsMain: "Attack first with your main weapon (Attack action), then the bonus attack unlocks.",
        bonusAlreadyUsed: 'Bonus action already used this turn.',
        bonusAction: (label: string) => `Bonus action: ${label}`,
        bonusBtnOffhand: 'Bonus 🗡️ Off-hand',
        bonusBtnFrenzy: 'Bonus 🗡️ Frenzy',
        bonusBtnWar: 'Bonus 🗡️ War',
        bonusBtnShield: 'Bonus 🛡️ Shield bash',
        shieldBashName: 'Shield bash',
        shieldBashLabel: (name: string) => `Shield bash: ${name}`,
        afterMainAttack: 'After your main attack',
        bonusUsed: 'Bonus used',
        spell: 'Spell',
        noSpellKnown: 'No spell known!',
        cantripsGroup: 'Cantrips (Unlimited)',
        leveledSpellsGroup: 'Leveled Spells',
        resourceSlot: 'Resource / Slot',
        freeCantrip: 'Free (Cantrip)',
        noSlots: 'No slots',
        levelPrefix: 'Level ',
        pactSlotLabel: 'Pact slot lv.',
        bandFar: '🏹 FAR',
        bandNear: '➡ AT RANGE',
        bonusNeedsMelee: 'Target not in melee reach',
        advanceBtn: 'Close In 🏃',
        chargeBtn: 'Charge ⚡',
        advanceTitle: 'Target out of melee reach — this action closes one distance band (no strike this turn).',
        chargeTitle: 'Charge: close the distance AND strike in the same action (mount or rage).',
        aoePickTargets: 'Area — pick specific targets (overrides the list above)',
        player: 'Player',
        enemyHp: (cur: number, max: number) => `Enemy, HP: ${cur}/${max}`,
        castSpell: 'Cast the Spell ✨',
        itemToUse: 'Item to Use',
        noConsumable: 'No consumable item available in your inventory!',
        noEffectDesc: 'No effect description',
        useItem: "Use the Item 🧪",
        dodgeDescription: 'Taking the Dodge action lets you focus on defense. Until the start of your next turn, any attack roll against you has Disadvantage, and you gain a defensive bonus.',
        activateDodge: 'Activate Dodge 🛡️',
        abilities: 'Class abilities',
        abilityRage: 'Rage',
        abilityRageHint: 'Bonus action — +2 damage, resistance to physical damage (10 rounds).',
        abilitySecondWind: 'Second Wind',
        abilitySecondWindHint: 'Bonus action — regain 1d10 + level HP.',
        abilityActionSurge: 'Action Surge',
        abilityActionSurgeHint: 'Free — one extra full Attack action this turn.',
        abilityLayOnHands: 'Lay on Hands',
        abilityLayOnHandsHint: 'Action — heal your missing HP from the pool.',
        abilityBardic: 'Bardic Inspiration',
        abilityBardicHint: 'Bonus action — bank an inspiration die for your next rolls.',
        abilityFlurry: 'Flurry of Blows',
        abilityFlurryHint: 'Bonus action, 1 ki — two unarmed strikes (after your Attack).',
        abilityPatient: 'Patient Defense',
        abilityPatientHint: 'Bonus action, 1 ki — Dodge as a bonus action.',
        abilityLucky: 'Lucky',
        abilityLuckyHint: '1 luck point — advantage on your next roll.',
        abilityCunningHide: 'Cunning: Hide',
        abilityCunningHideHint: 'Bonus action — slip out of sight: advantage on your next attack.',
        abilityCunningDash: 'Cunning: Dash/Disengage',
        abilityCunningDashHint: 'Bonus action — reposition without provoking attacks.',
        abilityPreserveLife: 'Channel: Preserve Life',
        abilityPreserveLifeHint: 'Action, 1 Channel Divinity — heal up to 5 × level HP (max half your HP).',
        abilityGuidedStrike: 'Channel: Guided Strike',
        abilityGuidedStrikeHint: '1 Channel Divinity — +10 on your next attack roll.',
        abilityCreateSlot: 'Font of Magic',
        abilityCreateSlotHint: '2 sorcery points — create a level-1 spell slot.',
        abilitySuperiority: 'Maneuver',
        abilitySuperiorityHint: '1 superiority die — your next weapon hit this round deals bonus damage.',
        abilityWildShape: 'Wild Shape',
        abilityWildShapeHint: 'Action — beast form: gain 2 × level temporary HP (10 rounds).',
        abilityFamiliar: 'Familiar: Help',
        abilityFamiliarHint: 'Bonus action, 1/short rest — your familiar harries the foe: advantage on your next attack.',
        abilityDivineSmite: 'Divine Smite',
        abilityDivineSmiteHint: 'Burn a spell slot — your next weapon hit deals +2d8 radiant (+1d8 per slot level above 1st).',
        abilityRecklessAttack: 'Reckless Attack',
        abilityRecklessAttackHint: 'Free — advantage on your melee attacks this turn; attacks against you have advantage until your next turn.',
        abilityStunningStrike: 'Stunning Strike',
        abilityStunningStrikeHint: '1 ki — your next weapon hit forces a CON save or the target is stunned.',
        abilityStepOfWind: 'Step of the Wind',
        abilityStepOfWindHint: 'Bonus action, 1 ki — Dash and Disengage: reposition freely.',
        abilityTurnUndead: 'Channel: Turn Undead',
        abilityTurnUndeadHint: 'Action, 1 Channel Divinity — undead within 30 ft flee (WIS save vs your spell DC).',
        abilityEldritchMind: 'Pact Focus',
        abilityEldritchMindHint: 'Bonus action, 1/short rest — your patron sharpens your aim: advantage on your next spell attack.',
        abilityNaturalRecovery: 'Natural Recovery',
        abilityNaturalRecoveryHint: 'Recover spell slots (half your level, rounded up) — 1/long rest.',
        abilityNeedsSlot: 'No spell slot left.',
        abilityMeleeOnly: 'Melee weapon required.',
        abilityDivineSense: 'Divine Sense',
        abilityDivineSenseHint: 'Action — detect celestials, fiends and undead within 60 ft (the DM answers honestly).',
        abilitySacredWeapon: 'Channel: Sacred Weapon',
        abilitySacredWeaponHint: 'Action, 1 Channel Divinity — +CHA to your weapon attack rolls for 10 rounds.',
        abilityVowOfEnmity: 'Channel: Vow of Enmity',
        abilityVowOfEnmityHint: 'Bonus action, 1 Channel Divinity — advantage on your attacks against your sworn foe (10 rounds).',
        abilityNaturesWrath: "Channel: Nature's Wrath",
        abilityNaturesWrathHint: 'Action, 1 Channel Divinity — spectral vines: STR save or the target is restrained.',
        abilityCavalierChallenge: 'Channel: Cavalier Challenge',
        abilityCavalierChallengeHint: 'Bonus action, 1 Channel Divinity — challenge a foe: it focuses its attacks on YOU.',
        abilityDivineIntervention: 'Divine Intervention',
        abilityDivineInterventionHint: 'Action — d100 ≤ your level: your deity intervenes with a miracle. 1/long rest.',
        abilityPrimevalAwareness: 'Primeval Awareness',
        abilityPrimevalAwarenessHint: 'Action, 1 level-1 slot — sense aberrations, celestials, dragons, elementals, fey, fiends and undead within 1 mile.',
        abilityMetaQuickened: 'Metamagic: Quickened',
        abilityMetaQuickenedHint: '2 sorcery points — your next spell this turn costs a BONUS ACTION instead of your action.',
        abilityMetaHeightened: 'Metamagic: Heightened',
        abilityMetaHeightenedHint: '3 sorcery points — the target of your next save-spell rolls its save with DISADVANTAGE.',
        abilityWholeness: 'Wholeness of Body',
        abilityWholenessHint: 'Action — regain 3 × monk level HP. 1/long rest.',
        bonusBtnMartial: 'Bonus 👊 Strike',
        martialArtsLabel: 'Martial Arts',
        unarmedStrike: 'Unarmed Strike',
        allEnemies: 'All enemies (area spell)',
        allCombatants: 'Whole area — allies included (friendly fire)',
        polearmButt: 'Butt-end strike (Polearm Master)',
        powerAttackGWM: 'Great Weapon Master: -5 to hit / +10 damage',
        powerAttackSharp: 'Sharpshooter: -5 to hit / +10 damage',
        needsAttackFirst: 'Attack first with your main action.',
        combatOnlyShort: 'Combat only.',
        bonusUsedShort: 'Bonus action already used.',
        actionUsedShort: 'Main action already used.',
    },
    fr: {
        offhand: (name: string) => `Off-hand : ${name}`,
        frenzy: (name: string) => `Frénésie : ${name}`,
        warPriest: (name: string, uses: number) => `Prêtre de guerre : ${name} (${uses})`,
        waitingTurnOf: (name: string) => `En attente — tour de ${name}…`,
        waitingUpdate: 'En attente de la mise à jour du combat…',
        incapacitatedBanner: (cond: string) => `${cond} — vous ne pouvez pas agir ce tour. Votre tour passera automatiquement.`,
        dyingBanner: 'Inconscient (0 PV) — jets de mort en cours. Vous ne pouvez pas agir.',
        combatActionsHeader: '⚔️ Actions de Combat (Ton Tour)',
        actionAvailable: 'Action Disponible',
        attack: 'Attaquer',
        spells: 'Sorts',
        items: 'Objets',
        dodge: 'Esquiver',
        equippedWeapon: 'Arme Équipée',
        noWeaponEquipped: "Aucune arme équipée ! Ouvrez l'inventaire pour vous équiper.",
        damage: 'dégâts',
        target: 'Cible',
        noEnemyTarget: 'Aucune cible ennemie en combat.',
        hpLabel: 'PV',
        acLabel: 'CA',
        resolving: 'Résolution…',
        attackBtn: 'Attaque ⚔️',
        bonusNeedsMain: "Attaque d'abord avec ton arme principale (action Attaque), puis l'attaque bonus se débloque.",
        bonusAlreadyUsed: 'Action bonus déjà utilisée ce tour.',
        bonusAction: (label: string) => `Action bonus : ${label}`,
        bonusBtnOffhand: 'Bonus 🗡️ Main gauche',
        bonusBtnFrenzy: 'Bonus 🗡️ Frénésie',
        bonusBtnWar: 'Bonus 🗡️ Guerre',
        bonusBtnShield: 'Bonus 🛡️ Coup de bouclier',
        shieldBashName: 'Coup de bouclier',
        shieldBashLabel: (name: string) => `Coup de bouclier : ${name}`,
        afterMainAttack: 'Après ton attaque principale',
        bonusUsed: 'Bonus utilisé',
        spell: 'Sortilège',
        noSpellKnown: 'Aucun sort connu !',
        cantripsGroup: 'Tours de magie (Cantrips - Illimités)',
        leveledSpellsGroup: 'Sorts de Niveau',
        resourceSlot: 'Ressource / Slot',
        freeCantrip: 'Gratuit (Cantrip)',
        noSlots: "Pas d'emplacements",
        levelPrefix: 'Niveau ',
        pactSlotLabel: 'Pacte — niv.',
        bandFar: '🏹 LOIN',
        bandNear: '➡ À DISTANCE',
        bonusNeedsMelee: 'Cible pas au contact',
        advanceBtn: 'Se rapprocher 🏃',
        chargeBtn: 'Charger ⚡',
        advanceTitle: 'Cible hors de portée de mêlée — cette action te rapproche d\'une bande (pas de frappe ce tour-ci).',
        chargeTitle: 'Charge : rapprochement ET frappe dans la même action (monture ou rage).',
        aoePickTargets: 'Zone — choisis des cibles précises (remplace la liste au-dessus)',
        player: 'Joueur',
        enemyHp: (cur: number, max: number) => `Ennemi, PV: ${cur}/${max}`,
        castSpell: 'Lancer le Sort ✨',
        itemToUse: 'Objet à Utiliser',
        noConsumable: 'Aucun objet consommable disponible dans votre inventaire !',
        noEffectDesc: 'Aucune description d\'effet',
        useItem: "Utiliser l'Objet 🧪",
        dodgeDescription: "Prendre l'action d'esquive (Dodge) vous permet de vous concentrer sur la défense. Jusqu'au début de votre prochain tour, tout jet d'attaque contre vous aura un Désavantage, et vous gagnez un bonus défensif.",
        activateDodge: "Activer l'Esquive 🛡️",
        abilities: 'Capacités de classe',
        abilityRage: 'Rage',
        abilityRageHint: 'Action bonus — +2 dégâts, résistance aux dégâts physiques (10 rounds).',
        abilitySecondWind: 'Second souffle',
        abilitySecondWindHint: 'Action bonus — regagne 1d10 + niveau PV.',
        abilityActionSurge: "Sursaut d'action",
        abilityActionSurgeHint: 'Gratuit — une action Attaquer complète en plus ce tour.',
        abilityLayOnHands: 'Imposition des mains',
        abilityLayOnHandsHint: 'Action — soigne tes PV manquants depuis la réserve.',
        abilityBardic: 'Inspiration bardique',
        abilityBardicHint: 'Action bonus — mets en réserve un dé d\'inspiration pour tes prochains jets.',
        abilityFlurry: 'Déluge de coups',
        abilityFlurryHint: 'Action bonus, 1 ki — deux frappes à mains nues (après ton Attaque).',
        abilityPatient: 'Défense patiente',
        abilityPatientHint: 'Action bonus, 1 ki — Esquive en action bonus.',
        abilityLucky: 'Chanceux',
        abilityLuckyHint: '1 point de chance — avantage sur ton prochain jet.',
        abilityCunningHide: 'Ruse : Se cacher',
        abilityCunningHideHint: 'Action bonus — disparais des regards : avantage sur ta prochaine attaque.',
        abilityCunningDash: 'Ruse : Repli/Sprint',
        abilityCunningDashHint: 'Action bonus — repositionne-toi sans provoquer d\'attaques.',
        abilityPreserveLife: 'Canalisation : Préserver la vie',
        abilityPreserveLifeHint: 'Action, 1 Canalisation — soigne jusqu\'à 5 × niveau PV (max moitié de tes PV).',
        abilityGuidedStrike: 'Canalisation : Frappe guidée',
        abilityGuidedStrikeHint: '1 Canalisation — +10 sur ton prochain jet d\'attaque.',
        abilityCreateSlot: 'Source de magie',
        abilityCreateSlotHint: '2 points de sorcellerie — crée un emplacement de niveau 1.',
        abilitySuperiority: 'Manœuvre',
        abilitySuperiorityHint: '1 dé de supériorité — ta prochaine attaque d\'arme réussie ce round inflige des dégâts bonus.',
        abilityWildShape: 'Forme sauvage',
        abilityWildShapeHint: 'Action — forme animale : 2 × niveau PV temporaires (10 rounds).',
        abilityFamiliar: 'Familier : Aide',
        abilityFamiliarHint: 'Action bonus, 1/repos court — ton familier harcèle la cible : avantage sur ta prochaine attaque.',
        abilityDivineSmite: 'Châtiment divin',
        abilityDivineSmiteHint: 'Brûle un emplacement de sort — ta prochaine attaque réussie inflige +2d8 radiants (+1d8 par niveau au-dessus du 1er).',
        abilityRecklessAttack: 'Attaque téméraire',
        abilityRecklessAttackHint: 'Gratuit — avantage sur tes attaques de mêlée ce tour ; les attaques contre toi ont l\'avantage jusqu\'à ton prochain tour.',
        abilityStunningStrike: 'Frappe étourdissante',
        abilityStunningStrikeHint: '1 ki — ta prochaine attaque réussie impose une sauvegarde de CON ou la cible est étourdie.',
        abilityStepOfWind: 'Pas du vent',
        abilityStepOfWindHint: 'Action bonus, 1 ki — Sprint et Désengagement : tu te repositionnes librement.',
        abilityTurnUndead: 'Canalisation : Renvoi des morts-vivants',
        abilityTurnUndeadHint: 'Action, 1 Canalisation — les morts-vivants à 9 m fuient (sauvegarde de SAG contre ton DD de sort).',
        abilityEldritchMind: 'Focalisation du pacte',
        abilityEldritchMindHint: 'Action bonus, 1/repos court — ton patron guide ta main : avantage sur ta prochaine attaque de sort.',
        abilityNaturalRecovery: 'Récupération naturelle',
        abilityNaturalRecoveryHint: 'Récupère des emplacements de sort (moitié de ton niveau, arrondi au supérieur) — 1/repos long.',
        abilityNeedsSlot: 'Aucun emplacement de sort.',
        abilityMeleeOnly: 'Arme de mêlée requise.',
        abilityDivineSense: 'Perception divine',
        abilityDivineSenseHint: 'Action — détecte célestes, fiélons et morts-vivants à 18 m (le MJ répond honnêtement).',
        abilitySacredWeapon: 'Canalisation : Arme sacrée',
        abilitySacredWeaponHint: "Action, 1 Canalisation — +mod. CHA à tes jets d'attaque d'arme pendant 10 rounds.",
        abilityVowOfEnmity: 'Canalisation : Vœu d\'inimitié',
        abilityVowOfEnmityHint: 'Action bonus, 1 Canalisation — avantage sur tes attaques contre ton ennemi juré (10 rounds).',
        abilityNaturesWrath: 'Canalisation : Courroux de la nature',
        abilityNaturesWrathHint: 'Action, 1 Canalisation — lianes spectrales : sauvegarde de FOR ou la cible est ENTRAVÉE.',
        abilityCavalierChallenge: 'Canalisation : Défi du cavalier',
        abilityCavalierChallengeHint: 'Action bonus, 1 Canalisation — défie un ennemi : il concentre ses assauts sur TOI.',
        abilityDivineIntervention: 'Intervention divine',
        abilityDivineInterventionHint: 'Action — d100 ≤ ton niveau : ta divinité intervient par un miracle. 1/repos long.',
        abilityPrimevalAwareness: 'Conscience primitive',
        abilityPrimevalAwarenessHint: 'Action, 1 emplacement niv. 1 — perçois aberrations, célestes, dragons, élémentaires, fées, fiélons et morts-vivants à 1,5 km.',
        abilityMetaQuickened: 'Métamagie : Sort accéléré',
        abilityMetaQuickenedHint: '2 pts de sorcellerie — ton prochain sort ce tour coûte une ACTION BONUS au lieu de ton action.',
        abilityMetaHeightened: 'Métamagie : Sort intensifié',
        abilityMetaHeightenedHint: '3 pts de sorcellerie — la cible de ton prochain sort à sauvegarde jette avec DÉSAVANTAGE.',
        abilityWholeness: 'Plénitude du corps',
        abilityWholenessHint: 'Action — regagne 3 × niveau de moine PV. 1/repos long.',
        bonusBtnMartial: 'Bonus 👊 Frappe',
        martialArtsLabel: 'Arts martiaux',
        unarmedStrike: 'Frappe à mains nues',
        allEnemies: 'Tous les ennemis (sort de zone)',
        allCombatants: 'Toute la zone — alliés compris (tir ami)',
        polearmButt: 'Coup du talon (Maître d\'armes d\'hast)',
        powerAttackGWM: 'Maître des armes de guerre : -5 au jet / +10 dégâts',
        powerAttackSharp: 'Tireur d\'élite : -5 au jet / +10 dégâts',
        needsAttackFirst: "Attaque d'abord avec ton action principale.",
        combatOnlyShort: 'En combat uniquement.',
        bonusUsedShort: 'Action bonus déjà utilisée.',
        actionUsedShort: 'Action principale déjà utilisée.',
    },
} as const;

// ── CombatTracker ──
export const COMBAT_TRACKER_TEXTS = {
    en: {
        mainActionTitle: 'Main Action (Green = Available, Gray = Used)',
        bonusActionTitle: 'Bonus Action (Yellow = Available, Gray = Used)',
        reactionTitle: 'Reaction (Purple = Available, Gray = Used)',
        extraAttackTitle: 'Extra Attack (Blue = Available, Gray = Used)',
        riddenMount: '🐴 ridden — acts with the rider',
        rangeNear: '↔ near',
        rangeFar: '🏹 far',
        rangeNearTitle: 'A few strides away — a melee attack closes in for free.',
        rangeFarTitle: 'Far away — closing in takes your attack, or use a ranged/thrown weapon.',
        target: '🎯 TARGET',
        init: 'Init',
        usesRemaining: (n: number) => `${n} uses remaining`,
        currentTurn: 'Current turn',
        reference: 'Reference',
        combat: 'Combat',
        initiative: 'Initiative',
        round: 'Round',
        enemies: 'Enemies',
        endMyTurn: 'End my turn',
        waiting: 'Waiting',
        endTurnTitle: 'End your turn — the enemies play next',
        otherCombatantsTurn: "Other combatants' turn",
        endCombat: 'End the combat',
        end: 'End',
        combatRolls: 'Combat rolls',
        playerLegend: '● player',
        enemyLegend: '● enemy/DM',
        rollsEmpty: 'Attack and damage rolls will appear here.',
        outOfFight: 'Out of the fight (alive)',
        fled: 'fled',
        surrendered: 'surrendered',
    },
    fr: {
        mainActionTitle: 'Action Principale (Vert = Disponible, Gris = Utilisé)',
        bonusActionTitle: 'Action Bonus (Jaune = Disponible, Gris = Utilisé)',
        reactionTitle: 'Réaction (Violet = Disponible, Gris = Utilisé)',
        extraAttackTitle: 'Attaque Supplémentaire (Bleu = Disponible, Gris = Utilisé)',
        riddenMount: '🐴 en selle — agit avec le cavalier',
        rangeNear: '↔ proche',
        rangeFar: '🏹 loin',
        rangeNearTitle: 'À quelques pas — une attaque de mêlée engage gratuitement.',
        rangeFarTitle: 'Loin — se rapprocher coûte ton attaque, ou utilise une arme à distance/de jet.',
        target: '🎯 CIBLE',
        init: 'Init',
        usesRemaining: (n: number) => `${n} utilisations restantes`,
        currentTurn: 'Tour actuel',
        reference: 'Référence',
        combat: 'Combat',
        initiative: 'Initiative',
        round: 'Round',
        enemies: 'Ennemis',
        endMyTurn: 'Terminer mon tour',
        waiting: 'En attente',
        endTurnTitle: 'Terminer ton tour — les ennemis jouent ensuite',
        otherCombatantsTurn: 'Tour des autres combattants',
        endCombat: 'Terminer le combat',
        end: 'Fin',
        combatRolls: 'Jets de combat',
        playerLegend: '● joueur',
        enemyLegend: '● ennemi/MJ',
        rollsEmpty: "Les jets d'attaque et de dégâts s'afficheront ici.",
        outOfFight: 'Hors combat (vivants)',
        fled: 'en fuite',
        surrendered: 'reddition',
    },
} as const;
