#!/usr/bin/env python3
"""
Fabrique data/monsterIndex.ts — l'annuaire LEGER des 401 monstres.

Pourquoi ce fichier existe
--------------------------
La page d'accueil doit pouvoir NOMMER, CLASSER et CHERCHER les monstres sans
charger data/monsterData2.ts (1,5 Mo de blocs SRD complets, pensés pour le
moteur de combat). L'annuaire ne porte que ce qu'un visiteur voit : la cle,
le nom, le facteur de puissance, la CA, les PV, le type et la taille.

~25 Ko pour 401 entrees. Le lore (419 Ko) et le bestiaire (1,5 Mo) restent
differes, et l'explorateur de l'accueil devient instantane.

Usage
-----
    python tools/gen_monster_index.py

Idempotent. A relancer apres toute regeneration du bestiaire.
"""
import io
import json
import os
import sys

RACINE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    src = os.path.join(RACINE, 'data', 'monsterData2.ts')
    s = io.open(src, encoding='utf-8').read()
    j = s.index('{', s.index('export const SRD_MONSTERS'))
    D = json.loads(s[j:s.rindex('}') + 1])

    lignes = []
    for cle in sorted(D):
        m = D[cle]
        base = m.get('base', {})
        hp = base.get('hp', {})
        e = {
            'id': cle,
            'name': m.get('name') or cle,
            'cr': m.get('cr', 0),
            'ac': base.get('ac', 10),
            'hp': hp.get('base', 1),
            'type': base.get('type', '?'),
            'size': base.get('size', '?'),
        }
        lignes.append('    ' + json.dumps(e, ensure_ascii=False) + ',')

    sortie = os.path.join(RACINE, 'data', 'monsterIndex.ts')
    io.open(sortie, 'w', encoding='utf-8', newline='').write(
        "// AUTO-GENERATED by tools/gen_monster_index.py — NE PAS EDITER A LA MAIN.\n"
        "//\n"
        "// L'annuaire LEGER du bestiaire : de quoi nommer, classer et chercher les\n"
        "// 401 monstres sans charger data/monsterData2.ts (1,5 Mo). L'illustration se\n"
        "// deduit de la cle — public/art/monsters/<id>.webp — et le texte vit dans\n"
        "// data/monsterLore.ts, charge a la demande.\n"
        "//\n"
        "// Regenerer apres toute reconstruction du bestiaire.\n\n"
        "export interface MonsterIndexEntry {\n"
        "    id: string;\n"
        "    name: string;\n"
        "    cr: number;\n"
        "    ac: number;\n"
        "    hp: number;\n"
        "    type: string;\n"
        "    size: string;\n"
        "}\n\n"
        "export const MONSTER_INDEX: MonsterIndexEntry[] = [\n"
        + "\n".join(lignes) + "\n];\n"
    )
    print(f'entrees : {len(lignes)}')
    print(f'poids   : {os.path.getsize(sortie) / 1024:.0f} Ko')


if __name__ == '__main__':
    sys.exit(main())
