/**
 * Les textes (fr / en) des ecrans de ce dossier, une table par composant.
 *
 * Rassembles ici le 2026-08-25 (R8 du rangement) : chaque table vivait en
 * tete de son composant sous le nom TRANS ; le composant l'importe
 * desormais sous ce meme alias, ses usages n'ont pas change. Contenu
 * inchange.
 */

// ── CampaignBoardPanel ──
export const CAMPAIGN_BOARD_PANEL_TEXTS = {
    en: {
        tabSpine: 'Spine',
        tabBranch: 'Branch',
        tabState: 'State',
        tabTimeline: 'Timeline',
        windowTitle: 'Campaign Board',
        defaultSubtitle: 'Director state, branch plan, and campaign timeline',
        mainArc: 'Main Arc',
        villain: 'Villain',
        motivation: 'Motivation',
        currentChapter: 'Current Chapter',
        legacySave: 'Legacy save: parsed manifest metadata is not available.',
        noManifest: 'No adventure manifest loaded yet.',
        chapters: 'Chapters',
        active: 'active',
        noChapters: 'No structured chapters available.',
        activeBranch: 'Active Branch',
        min: 'min',
        noActiveBranch: 'No active side branch. The DM can call request_branch_plan when the player makes a major detour.',
        reconnectHooks: 'Reconnect Hooks',
        noReconnectHooks: 'No reconnect hooks planned.',
        branchHistory: 'Branch History',
        noBranchHistory: 'No branch history yet.',
        directorState: 'Director State',
        chapter: 'Chapter',
        scene: 'Scene',
        objective: 'Objective',
        auto: 'auto',
        none: 'none',
        protectedSecrets: 'Protected secrets',
        secretsHint: 'Hidden from this player-facing board, still available to the director context.',
        canonFacts: 'Canon Facts',
        noCanonFacts: 'No canon facts recorded yet.',
        worldClocks: 'World Clocks',
        noWorldClocks: 'No active world clocks.',
        recentEvents: 'Recent Campaign Events',
        noEvents: 'No campaign events recorded yet.',
    },
    fr: {
        tabSpine: 'Trame',
        tabBranch: 'Embranchement',
        tabState: 'État',
        tabTimeline: 'Chronologie',
        windowTitle: 'Tableau de campagne',
        defaultSubtitle: 'État du metteur en scène, plan d’embranchement et chronologie de la campagne',
        mainArc: 'Arc principal',
        villain: 'Antagoniste',
        motivation: 'Motivation',
        currentChapter: 'Chapitre en cours',
        legacySave: 'Sauvegarde héritée : les métadonnées du manifeste analysé ne sont pas disponibles.',
        noManifest: 'Aucun manifeste d’aventure chargé pour l’instant.',
        chapters: 'Chapitres',
        active: 'actif',
        noChapters: 'Aucun chapitre structuré disponible.',
        activeBranch: 'Embranchement actif',
        min: 'min',
        noActiveBranch: 'Aucun embranchement secondaire actif. Le MJ peut appeler request_branch_plan quand le joueur fait un détour majeur.',
        reconnectHooks: 'Accroches de reconnexion',
        noReconnectHooks: 'Aucune accroche de reconnexion prévue.',
        branchHistory: 'Historique des embranchements',
        noBranchHistory: 'Aucun historique d’embranchement pour l’instant.',
        directorState: 'État du metteur en scène',
        chapter: 'Chapitre',
        scene: 'Scène',
        objective: 'Objectif',
        auto: 'auto',
        none: 'aucun',
        protectedSecrets: 'Secrets protégés',
        secretsHint: 'Cachés de ce tableau visible par le joueur, mais toujours disponibles pour le contexte du metteur en scène.',
        canonFacts: 'Faits canoniques',
        noCanonFacts: 'Aucun fait canonique enregistré pour l’instant.',
        worldClocks: 'Horloges du monde',
        noWorldClocks: 'Aucune horloge du monde active.',
        recentEvents: 'Événements récents de la campagne',
        noEvents: 'Aucun événement de campagne enregistré pour l’instant.',
    },
} as const;

// ── GameWindow ──
export const GAME_WINDOW_TEXTS = {
    en: { close: 'Close' },
    fr: { close: 'Fermer' },
} as const;

// ── InGameMenus ──
export const IN_GAME_MENUS_TEXTS = {
    en: {
        // Equipment slot labels
        head: 'Head', neck: 'Neck', back: 'Back', chest: 'Chest', waist: 'Waist',
        hands: 'Hands', mainHand: 'Main hand', offHand: 'Off hand', ranged: 'Ranged weapon', ring: 'Ring', ring2: 'Ring 2',
        legs: 'Legs', feet: 'Feet',
        // Inventory panel
        inventory: 'Inventory',
        visibleItems: 'visible items',
        carried: 'lb carried',
        equipment: 'Equipment',
        backpack: 'Backpack',
        consumables: 'Consumables',
        gp: 'gp',
        backpackEmpty: 'Your backpack is empty.',
        noConsumables: 'No consumables available.',
        // Equip warnings
        twoHandedWarn: 'You cannot equip an off-hand item while holding a two-handed weapon.',
        offHandWarn: 'Off-hand weapons must be LIGHT melee weapons (SRD two-weapon fighting).',
        attunementWarn: 'Attunement limit reached: you can be attuned to at most 3 magic items at once (SRD).',
        overloaded: 'OVERLOADED (drop or stash gear)',
        // Item lines
        damage: 'damage',
        ac: 'AC',
        noMechanicalEffect: 'No mechanical effect',
        // Equipment view
        combatReady: 'Combat ready',
        speed: 'Speed',
        hp: 'HP',
        equippedAttacks: 'Equipped attacks',
        noWeaponEquipped: 'No weapon equipped.',
        empty: 'Empty',
        noItemEquipped: 'No item equipped',
        attack: 'Attack',
        use: 'Use',
        mainHandBtn: 'Main',
        offHandBtn: 'Off-hand',
        rangedBtn: 'Ranged',
        companionsHeader: '🐾 Companions & bound creatures',
        lvlShort: 'lvl',
        hpShort: 'HP',
        acShort: 'AC',
        boundTag: '(bound)',
        familiarHelpHint: 'Help: advantage on the next attack (1/short rest)',
        mountedOn: '🐎 In the saddle',
        mountedOff: '🚶 On foot',
        mountedDown: '💀 Down',
        mountUp: 'Mount up',
        dismount: 'Dismount',
        mountedHint: 'Mounted charge active: a melee attack on a distant enemy closes in AND strikes in one action.',
        dismountedHint: 'No mounted charge while on foot — melee attacks on distant enemies close the distance instead.',
        mountDownHint: 'Your mount is down: you cannot ride it until it recovers (a long rest, or a new mount).',
        dropBtn: 'Drop',
        dropTitle: 'Throw this item away (it stays in the scene — the DM may make use of it)',
        dropConfirm: (name: string, qty: number) => `Throw away ${qty > 1 ? `${qty}x ` : ''}${name}? The item will be left behind.`,
        dropEquippedHint: 'Unequip the item first, then drop it.',
        advantagesHeader: '⭐ Active advantages',
        advTagAttack: 'Attack rolls',
        advTagDefense: 'Defense — attackers have disadvantage',
        unequip: 'Unequip',
        equip: 'Equip',
        // Character sheet
        level: 'Level',
        armorClass: 'Armor Class',
        base: 'base',
        initiative: 'Initiative',
        hitPoints: 'Hit Points',
        temp: 'Temp',
        max: 'Max',
        experience: 'Experience',
        maxLevel: 'MAX LEVEL',
        xpBeforeLevel1: 'XP until level',
        xpBeforeLevel2: '',
        pendingASI: 'Pending ability points',
        clickAbility: 'Click an ability to add +1 (max 20).',
        choiceRequired: 'choice required!',
        mustChoose1: 'Your',
        mustChoose2: 'level',
        mustChoose3: 'must choose its specialization. This choice unlocks real mechanical abilities.',
        attacksSpells: 'Attacks & Spells',
        name: 'Name',
        attackCol: 'Attack',
        damageCol: 'Damage',
        properties: 'Properties',
        none: 'none',
        activeEffects: 'Active Effects',
        turnsShort: 'turn(s)',
        resources: 'Resources',
        slotLevel: 'Slot lvl.',
        pact: 'pact ',
        noLimitedResources: 'No limited resources for now.',
        spellsMagic: 'Spells & Magic',
        cantrips: 'Cantrips',
        preparedSpells: 'Prepared spells',
        knownSpells: 'Known spells',
        spellcastingAbility: 'Spellcasting ability',
        focus: 'Focus',
        abilitiesTraits: 'Abilities & Traits',
        noAbility: 'No abilities recorded.',
        proficiencies: 'Proficiencies',
        // Effect durations
        longRest: 'Long rest',
        shortRest: 'Short rest',
        concentration: 'Concentration',
        oneHour: '1 hour',
        eightHours: '8 hours',
        rounds: 'Rounds',
        permanent: 'Permanent',
    },
    fr: {
        head: 'Tête', neck: 'Cou', back: 'Dos', chest: 'Torse', waist: 'Taille',
        hands: 'Mains', mainHand: 'Main directrice', offHand: 'Main gauche', ranged: 'Arme à distance', ring: 'Anneau', ring2: 'Anneau 2',
        legs: 'Jambes', feet: 'Pieds',
        inventory: 'Inventaire',
        visibleItems: 'objets visibles',
        carried: 'lb portées',
        equipment: 'Équipement',
        backpack: 'Sac à dos',
        consumables: 'Consommables',
        gp: 'PO',
        backpackEmpty: 'Ton sac à dos est vide.',
        noConsumables: 'Aucun consommable disponible.',
        twoHandedWarn: "Vous ne pouvez pas équiper un objet en main gauche en tenant une arme à deux mains.",
        offHandWarn: 'Les armes en main gauche doivent être des armes de mêlée LÉGÈRES (combat à deux armes SRD).',
        attunementWarn: 'Limite d\'harmonisation atteinte : au plus 3 objets magiques harmonisés à la fois (SRD).',
        overloaded: 'SURCHARGÉ (déposez ou jetez de l\'équipement)',
        damage: 'dégâts',
        ac: 'CA',
        noMechanicalEffect: 'Aucun effet mécanique',
        combatReady: 'Prêt au combat',
        speed: 'Vitesse',
        hp: 'PV',
        equippedAttacks: 'Attaques équipées',
        noWeaponEquipped: 'Aucune arme équipée.',
        empty: 'Vide',
        noItemEquipped: 'Aucun objet équipé',
        attack: 'Attaque',
        use: 'Utiliser',
        mainHandBtn: 'Principale',
        // ui-m2 — « Off-hand » traînait dans la table FRANÇAISE.
        offHandBtn: 'Main gauche',
        rangedBtn: 'À distance',
        companionsHeader: '🐾 Compagnons & créatures liées',
        lvlShort: 'niv',
        hpShort: 'PV',
        acShort: 'CA',
        boundTag: '(lié)',
        familiarHelpHint: 'Aide : avantage sur la prochaine attaque (1/repos court)',
        mountedOn: '🐎 En selle',
        mountedOff: '🚶 À pied',
        mountedDown: '💀 À terre',
        mountUp: 'Monter en selle',
        dismount: 'Descendre',
        mountedHint: 'Charge montée active : une attaque de mêlée sur un ennemi éloigné se rapproche ET frappe en une action.',
        dismountedHint: 'Pas de charge montée à pied — l\'attaque de mêlée sur un ennemi éloigné devient un rapprochement.',
        mountDownHint: "Ta monture est à terre : impossible de la monter tant qu'elle ne récupère pas (repos long, ou une nouvelle monture).",
        dropBtn: 'Jeter',
        dropTitle: 'Abandonner cet objet (il reste dans la scène — le MJ peut en faire quelque chose)',
        dropConfirm: (name: string, qty: number) => `Jeter ${qty > 1 ? `${qty}x ` : ''}${name} ? L'objet sera abandonné sur place.`,
        dropEquippedHint: "Déséquipe d'abord l'objet, puis jette-le.",
        advantagesHeader: '⭐ Avantages actifs',
        advTagAttack: "Jets d'attaque",
        advTagDefense: 'Défense — attaquants à désavantage',
        unequip: 'Retirer',
        equip: 'Équiper',
        level: 'Niveau',
        armorClass: "Classe d'Armure",
        base: 'base',
        initiative: 'Initiative',
        hitPoints: 'Points de Vie',
        temp: 'Temp',
        max: 'Max',
        experience: 'Expérience',
        maxLevel: 'NIVEAU MAX',
        xpBeforeLevel1: 'XP avant le niveau',
        xpBeforeLevel2: '',
        pendingASI: 'Points de caractéristique en attente',
        clickAbility: 'Clique sur une caractéristique pour y ajouter +1 (max 20).',
        choiceRequired: 'choix requis !',
        mustChoose1: 'Ton',
        mustChoose2: 'niveau',
        mustChoose3: 'doit choisir sa spécialisation. Ce choix débloque de vraies capacités mécaniques.',
        attacksSpells: 'Attaques & Sorts',
        name: 'Nom',
        attackCol: 'Attaque',
        damageCol: 'Dégâts',
        properties: 'Propriétés',
        none: 'aucune',
        activeEffects: 'Effets actifs',
        turnsShort: 'tour(s)',
        resources: 'Ressources',
        slotLevel: 'Emplacement niv.',
        pact: 'pacte ',
        noLimitedResources: "Aucune ressource limitée pour l'instant.",
        spellsMagic: 'Sorts & Magie',
        cantrips: 'Tours de magie',
        preparedSpells: 'Sorts préparés',
        knownSpells: 'Sorts connus',
        spellcastingAbility: 'Caractéristique magique',
        focus: 'Focaliseur',
        abilitiesTraits: 'Capacités & Traits',
        noAbility: 'Aucune capacité enregistrée.',
        proficiencies: 'Maîtrises',
        longRest: 'Repos long',
        shortRest: 'Repos court',
        concentration: 'Concentration',
        oneHour: '1 heure',
        eightHours: '8 heures',
        rounds: 'Rounds',
        permanent: 'Permanent',
    },
} as const;

// ── JournalPanel ──
export const JOURNAL_PANEL_TEXTS = {
    en: {
        windowTitle: 'Adventure Journal',
        subtitle: (active: number, chronicle: number) => `${active} active quests / ${chronicle} chronicle entries`,
        tabPrologue: 'Prologue',
        tabQuests: 'Quests',
        tabPeople: 'NPCs',
        tabPlaces: 'Places',
        tabChronicle: 'Chronicle',
        noPrologue: 'No prologue recorded for this campaign.',
        objective: 'Objective',
        startingPoint: 'Starting point',
        theThreat: 'The threat',
        prologue: 'Prologue',
        adventureBeginning: 'Your adventure is only beginning.',
        statusActive: 'Active',
        statusCompleted: 'Completed',
        statusFailed: 'Failed',
        noNotableCharacter: 'No notable character recorded yet.',
        unknown: 'Unknown',
        noLocation: 'No discovered location yet.',
        chronicleEmpty: 'The chronicle will fill as the campaign unfolds.',
        new: 'New',
        tabGallery: 'Gallery',
        galleryEmpty: 'Generated scene images will collect here.',
        exportChronicle: 'Export the illustrated chronicle (HTML)',
        dayWord: 'Day',
    },
    fr: {
        windowTitle: 'Journal d’aventure',
        subtitle: (active: number, chronicle: number) => `${active} quêtes actives / ${chronicle} entrées de chronique`,
        tabPrologue: 'Prologue',
        tabQuests: 'Quêtes',
        tabPeople: 'PNJ',
        tabPlaces: 'Lieux',
        tabChronicle: 'Chronique',
        noPrologue: 'Aucun prologue enregistré pour cette campagne.',
        objective: 'Objectif',
        startingPoint: 'Point de départ',
        theThreat: 'La menace',
        prologue: 'Prologue',
        adventureBeginning: 'Ton aventure ne fait que commencer.',
        statusActive: 'Active',
        statusCompleted: 'Terminée',
        statusFailed: 'Échouée',
        noNotableCharacter: 'Aucun personnage notable enregistré pour l’instant.',
        unknown: 'Inconnu',
        noLocation: 'Aucun lieu découvert pour l’instant.',
        chronicleEmpty: 'La chronique se remplira au fil de la campagne.',
        new: 'Nouveau',
        tabGallery: 'Galerie',
        galleryEmpty: 'Les images de scène générées se rassembleront ici.',
        exportChronicle: 'Exporter la chronique illustrée (HTML)',
        dayWord: 'Jour',
    },
} as const;

// ── LevelUpModal ──
export const LEVEL_UP_MODAL_TEXTS = {
    en: {
        levelUp: '🎊 LEVEL UP! 🎊',
        reachesLevel: (name: string, lvl: number) => <>{name} reaches <span className="font-bold text-amber-200">Level {lvl}</span>!</>,
        multiLevel: (n: number) => `(${n} levels gained at once — every improvement is counted)`,
        newAbilities: 'New Abilities',
        chooseYourPath: 'choose your path',
        choiceIsFinal: 'This choice is permanent and unlocks real mechanical abilities.',
        asiTitle: 'Ability Score Improvement',
        distribute: (n: number) => <>Distribute <span className="font-bold text-amber-200">{n} point{n > 1 ? 's' : ''}</span> (max 20 per ability).</>,
        remaining: 'Remaining:',
        later: 'Later',
        laterTitle: 'Your abilities are applied; the ability points stay available on the character sheet.',
        confirm: '✓ Confirm',
        featTitle: 'Or take a Feat',
        featHint: 'A feat costs 2 ability points and grants a unique permanent capability. Passive numbers apply automatically; the DM honors the rest.',
        featCost: '(2 points)',
        featSelected: 'Feat selected — remaining points can go to abilities.',
        spellsTitle: 'New spells',
        spellsHint: (n: number) => `Pick up to ${n} new spell${n > 1 ? 's' : ''} (cantrips included). You can always learn more later from the Spellbook.`,
        spellsPicked: (n: number, max: number) => `${n}/${max} picked`,
        cantripsGroup: 'Cantrips',
        levelGroup: (n: number) => `Level ${n}`,
    },
    fr: {
        levelUp: '🎊 NIVEAU SUPÉRIEUR ! 🎊',
        reachesLevel: (name: string, lvl: number) => <>{name} atteint le <span className="font-bold text-amber-200">Niveau {lvl}</span>!</>,
        multiLevel: (n: number) => `(${n} niveaux gagnés d'un coup — toutes les améliorations sont comptées)`,
        newAbilities: 'Nouvelles Capacités',
        chooseYourPath: 'choisis ta voie',
        choiceIsFinal: 'Ce choix est définitif et débloque de vraies capacités mécaniques.',
        asiTitle: 'Amélioration de Caractéristiques',
        distribute: (n: number) => <>Répartis <span className="font-bold text-amber-200">{n} point{n > 1 ? 's' : ''}</span> (max 20 par caractéristique).</>,
        remaining: 'Restant :',
        later: 'Plus tard',
        laterTitle: 'Tes capacités sont appliquées ; les points de caractéristique restent disponibles dans la fiche personnage.',
        confirm: '✓ Confirmer',
        featTitle: 'Ou prends un Don',
        featHint: 'Un don coûte 2 points de caractéristique et accorde une capacité permanente unique. Les bonus passifs s\'appliquent automatiquement ; le MJ honore le reste.',
        featCost: '(2 points)',
        featSelected: 'Don sélectionné — les points restants vont aux caractéristiques.',
        spellsTitle: 'Nouveaux sorts',
        spellsHint: (n: number) => `Choisis jusqu'à ${n} nouveau${n > 1 ? 'x' : ''} sort${n > 1 ? 's' : ''} (tours de magie inclus). Tu pourras toujours en apprendre plus tard via le Grimoire.`,
        spellsPicked: (n: number, max: number) => `${n}/${max} choisi${n > 1 ? 's' : ''}`,
        cantripsGroup: 'Tours de magie',
        levelGroup: (n: number) => `Niveau ${n}`,
    },
} as const;

// ── RuleCodexPanel ──
export const RULE_CODEX_PANEL_TEXTS = {
    en: {
        tabSpell: 'Spells',
        tabRule: 'Rules',
        tabItem: 'Items',
        tabCondition: 'Conditions',
        tabMonster: 'Monsters',
        windowTitle: 'SRD Codex',
        windowSubtitle: 'Rules, spells, items, conditions and bestiary references',
        searchPlaceholder: 'Search Codex',
        noEntry: 'No Codex entry found.',
        selectEntry: 'Select an entry.',
        cantrip: 'Cantrip',
        level: 'Level',
        condition: 'Condition',
        casting: 'Casting',
        range: 'Range',
        duration: 'Duration',
        components: 'Components',
        spellAttack: 'Spell attack',
        save: 'Save',
        success: 'success',
        damage: 'Damage',
        healing: 'Healing',
        castingAbility: 'casting ability',
        conditionOnFailure: 'Condition on failure',
        concentration: 'Concentration',
        movement: 'Movement',
        normal: 'normal',
        actions: 'Actions',
        type: 'Type',
        weight: 'Weight',
        ac: 'AC',
        properties: 'Properties',
        none: 'none',
        na: 'n/a',
        legacyEffect: 'Legacy effect',
        hp: 'HP',
        xp: 'XP',
        role: 'Role',
        size: 'Size',
        mechanics: 'Mechanics',
        viewReference: 'View reference',
    },
    fr: {
        tabSpell: 'Sorts',
        tabRule: 'Règles',
        tabItem: 'Objets',
        tabCondition: 'États',
        tabMonster: 'Monstres',
        windowTitle: 'Codex SRD',
        windowSubtitle: 'Règles, sorts, objets, états et références du bestiaire',
        searchPlaceholder: 'Rechercher dans le Codex',
        noEntry: 'Aucune entrée de Codex trouvée.',
        selectEntry: 'Sélectionne une entrée.',
        cantrip: 'Tour de magie',
        level: 'Niveau',
        condition: 'État',
        casting: 'Incantation',
        range: 'Portée',
        duration: 'Durée',
        components: 'Composantes',
        spellAttack: 'Attaque de sort',
        save: 'Sauvegarde',
        success: 'réussite',
        damage: 'Dégâts',
        healing: 'Soins',
        castingAbility: 'caractéristique d’incantation',
        conditionOnFailure: 'État en cas d’échec',
        concentration: 'Concentration',
        movement: 'Déplacement',
        normal: 'normal',
        actions: 'Actions',
        type: 'Type',
        weight: 'Poids',
        ac: 'CA',
        properties: 'Propriétés',
        none: 'aucune',
        na: 'n/a',
        legacyEffect: 'Effet hérité',
        hp: 'PV',
        xp: 'XP',
        role: 'Rôle',
        size: 'Taille',
        mechanics: 'Mécaniques',
        viewReference: 'Voir la référence',
    },
} as const;

// ── ShopPanel ──
export const SHOP_PANEL_TEXTS = {
    en: {
        buyTab: 'Buy',
        sellTab: 'Sell',
        buyBtn: 'Buy',
        sellBtn: 'Sell',
        gold: 'gp',
        purse: 'Purse',
        emptyStock: 'Nothing left on the stall.',
        emptyBag: 'Nothing to sell (equipped items must be unequipped first).',
        notEnoughGold: 'Not enough gold.',
        priceLabel: 'Price',
        sellFor: 'Sells for',
        leave: 'Leave the shop',
    },
    fr: {
        buyTab: 'Acheter',
        sellTab: 'Vendre',
        buyBtn: 'Acheter',
        sellBtn: 'Vendre',
        gold: 'po',
        purse: 'Bourse',
        emptyStock: "Plus rien sur l'étal.",
        emptyBag: "Rien à vendre (déséquipez d'abord les objets portés).",
        notEnoughGold: "Pas assez d'or.",
        priceLabel: 'Prix',
        sellFor: 'Rachat',
        leave: 'Quitter la boutique',
    },
} as const;

// ── SpellbookPanel ──
export const SPELLBOOK_PANEL_TEXTS = {
    en: {
        windowTitle: 'Spellbook',
        castingLabel: 'Spellcasting',
        mod: 'mod',
        spellSaveDC: 'Spell save DC',
        attackBonus: 'Attack bonus',
        maxPrepared: 'Max prepared spells',
        slots: 'Slots:',
        noSlots: 'No slots (cantrip-only caster, or non-caster).',
        restore: 'Restore',
        tabKnownSpells: 'Known spells',
        tabLearn: 'Learn',
        tabPrepared: 'Prepared',
        tabGrimoire: 'Spellbook',
        cantripsTitle: 'Cantrips (at will)',
        noCantrips: 'No cantrips.',
        knownSpellsTitle: 'Known spells',
        preparedSpellsTitle: 'Prepared spells',
        noKnownSpells: 'No known spells.',
        noPreparedSpells: 'No prepared spells. Prepare them in the Spellbook tab.',
        prepareSpells: 'Prepare spells',
        preparedCount: 'prepared',
        cantrips: 'Cantrips',
        levelN: (n: number) => `Level ${n}`,
        prepareRemove: 'Prepare / remove',
        details: 'Details',
        forget: 'Forget',
        emptyGrimoire: 'Empty spellbook. Learn spells in the “Learn” tab.',
        searchPlaceholder: (cls: string) => `${cls} spells…`,
        allLevels: 'All levels',
        levelOption: (n: number) => `Level ${n}`,
        allSchools: 'All schools',
        limitedNote: (lvl: number) => `Limited to your class spells, up to level ${lvl} (your current slots).`,
        known: 'Known',
        learn: '+ Learn',
        noMatch: 'No spell matches the filters.',
        noSpellcasting: 'This class does not cast spells.',
        selectSpellHint: 'Select a spell to see its description, components and parameters.',
        cantripBadge: 'Cantrip',
        higherLevels: 'At higher levels',
        effect: 'Effect',
        concentration: 'Concentration',
        ritual: 'Ritual',
        components: 'Components',
        castingTime: 'Casting time',
        range: 'Range',
        duration: 'Duration',
        targetArea: 'Target / area',
        material: 'Material',
        attack: 'Attack',
        save: 'Save',
        damage: 'Damage',
        healing: 'Healing',
        condition: 'Condition',
        melee: 'melee',
        ranged: 'ranged',
        saveHalf: 'half on success',
        saveNegates: 'negated on success',
        saveNone: 'no reduced effect',
        dcLabel: 'DC',
        cast: 'Cast',
        cantripWord: 'Cantrip',
        cantripShort: 'Cant',
        levelShort: (n: number) => `L${n}`,
        compV: 'V (verbal)',
        compS: 'S (somatic)',
        compM: 'M (material)',
        slotLabel: (key: string) => (key.startsWith('pact') ? `Pact ${key.replace('pact', 'lvl ')}` : `Lvl ${key}`),
    },
    fr: {
        windowTitle: 'Grimoire',
        castingLabel: 'Incantation',
        mod: 'mod',
        spellSaveDC: 'DD des sorts',
        attackBonus: 'Bonus d\'attaque',
        maxPrepared: 'Sorts préparés max',
        slots: 'Emplacements :',
        noSlots: 'Aucun emplacement (lanceur de tours de magie uniquement, ou non-magicien).',
        restore: 'Restaurer',
        tabKnownSpells: 'Sorts connus',
        tabLearn: 'Apprendre',
        tabPrepared: 'Préparés',
        tabGrimoire: 'Grimoire',
        cantripsTitle: 'Tours de magie (à volonté)',
        noCantrips: 'Aucun tour de magie.',
        knownSpellsTitle: 'Sorts connus',
        preparedSpellsTitle: 'Sorts préparés',
        noKnownSpells: 'Aucun sort connu.',
        noPreparedSpells: 'Aucun sort préparé. Prépare-les dans l’onglet Grimoire.',
        prepareSpells: 'Préparer des sorts',
        preparedCount: 'préparés',
        cantrips: 'Tours de magie',
        levelN: (n: number) => `Niveau ${n}`,
        prepareRemove: 'Préparer / retirer',
        details: 'Détails',
        forget: 'Oublier',
        emptyGrimoire: 'Grimoire vide. Apprends des sorts dans l’onglet « Apprendre ».',
        searchPlaceholder: (cls: string) => `Sorts de ${cls}…`,
        allLevels: 'Tous niveaux',
        levelOption: (n: number) => `Niveau ${n}`,
        allSchools: 'Toutes écoles',
        limitedNote: (lvl: number) => `Limité aux sorts de ta classe, jusqu'au niveau ${lvl} (tes emplacements actuels).`,
        known: 'Connu',
        learn: '+ Apprendre',
        noMatch: 'Aucun sort ne correspond aux filtres.',
        noSpellcasting: 'Cette classe ne lance pas de sorts.',
        selectSpellHint: 'Sélectionne un sort pour voir sa description, ses composantes et ses paramètres.',
        cantripBadge: 'Tour de magie',
        higherLevels: 'Aux niveaux supérieurs',
        effect: 'Effet',
        concentration: 'Concentration',
        ritual: 'Rituel',
        components: 'Composantes',
        castingTime: 'Incantation',
        range: 'Portée',
        duration: 'Durée',
        targetArea: 'Cible / zone',
        material: 'Matériel',
        attack: 'Attaque',
        save: 'Sauvegarde',
        damage: 'Dégâts',
        healing: 'Soins',
        condition: 'État',
        melee: 'au contact',
        ranged: 'à distance',
        saveHalf: 'moitié si réussi',
        saveNegates: 'annulé si réussi',
        saveNone: 'aucun effet réduit',
        dcLabel: 'DD',
        cast: 'Lancer',
        cantripWord: 'Tour de magie',
        cantripShort: 'Tour',
        levelShort: (n: number) => `N${n}`,
        compV: 'V (verbale)',
        compS: 'S (somatique)',
        compM: 'M (matérielle)',
        slotLabel: (key: string) => (key.startsWith('pact') ? `Pacte ${key.replace('pact', 'niv ')}` : `Niv ${key}`),
    },
} as const;
